--liquibase formatted sql

--changeset catalogimport:001-import-control-core
--comment Fase 1 domeinmodel: bronorganisatie, versieerbare importdefinitie, importkoppeling, taak, run en levering.

create table source_organisation (
    id                bigint generated by default as identity,
    code              varchar(50) not null,
    name              varchar(200) not null,
    organisation_type varchar(40) not null,
    active            boolean not null default true,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    constraint pk_source_organisation primary key (id),
    constraint uk_source_organisation_code unique (code)
);

create table import_definition (
    id                          bigint generated by default as identity,
    source_organisation_id      bigint not null,
    code                        varchar(50) not null,
    description                 varchar(200) not null,
    usage_type                  varchar(40) not null,
    superseded_by_definition_id bigint,
    based_on_definition_id      bigint,
    created_at                  timestamp with time zone not null,
    created_by                  varchar(100) not null,
    updated_at                  timestamp with time zone not null,
    constraint pk_import_definition primary key (id),
    constraint uk_import_definition_code unique (source_organisation_id, code),
    constraint fk_import_definition_source_organisation foreign key (source_organisation_id) references source_organisation (id),
    constraint fk_import_definition_superseded_by foreign key (superseded_by_definition_id) references import_definition (id),
    constraint fk_import_definition_based_on foreign key (based_on_definition_id) references import_definition (id)
);

-- active_marker is TRUE zolang de revisie ACTIVE is en NULL in elke andere toestand.
-- NULL-waarden botsen niet in een UNIQUE constraint, dus dit dwingt "hoogstens een actieve
-- revisie per definitie" op databaseniveau af (businessanalyse 14.14).
create table import_definition_revision (
    id                               bigint generated by default as identity,
    import_definition_id             bigint not null,
    revision_number                  integer not null,
    status                           varchar(40) not null,
    active_marker                    boolean,
    access_version                   integer not null,
    access_config_hash               varchar(64) not null,
    structure_version                integer not null,
    structure_config_hash            varchar(64) not null,
    record_rules_version             integer not null,
    record_rules_config_hash         varchar(64) not null,
    composite_config_hash            varchar(64) not null,
    identity_profile_kind            varchar(40) not null,
    identity_supplier_field          varchar(200) not null,
    identity_supplier_group_field    varchar(200) not null,
    identity_supplier_reference_field varchar(200) not null,
    identity_discount_code_field     varchar(200),
    based_on_revision_id             bigint,
    change_reason                    varchar(500),
    created_at                       timestamp with time zone not null,
    created_by                       varchar(100) not null,
    updated_at                       timestamp with time zone not null,
    approved_at                      timestamp with time zone,
    approved_by                      varchar(100),
    constraint pk_import_definition_revision primary key (id),
    constraint uk_import_definition_revision_number unique (import_definition_id, revision_number),
    constraint uk_import_definition_revision_active unique (import_definition_id, active_marker),
    constraint fk_import_definition_revision_definition foreign key (import_definition_id) references import_definition (id),
    constraint fk_import_definition_revision_based_on foreign key (based_on_revision_id) references import_definition_revision (id),
    constraint ck_import_definition_revision_identity check (
        (identity_profile_kind = 'THREE_PART' and identity_discount_code_field is null)
        or (identity_profile_kind = 'FOUR_PART_WITH_DISCOUNT_CODE' and identity_discount_code_field is not null)
    )
);

create table import_link (
    id                           bigint generated by default as identity,
    code                         varchar(50) not null,
    name                         varchar(200) not null,
    import_definition_id         bigint not null,
    supplier_organisation_id     bigint not null,
    library_code                 varchar(20) not null,
    library_search_supplier_code varchar(50),
    active                       boolean not null default true,
    created_at                   timestamp with time zone not null,
    updated_at                   timestamp with time zone not null,
    constraint pk_import_link primary key (id),
    constraint uk_import_link_code unique (code),
    constraint uk_import_link_scope unique (import_definition_id, supplier_organisation_id, library_code),
    constraint fk_import_link_definition foreign key (import_definition_id) references import_definition (id),
    constraint fk_import_link_supplier_organisation foreign key (supplier_organisation_id) references source_organisation (id)
);

create table catalog_import_task (
    id                      bigint generated by default as identity,
    import_link_id          bigint not null,
    name                    varchar(200) not null,
    active                  boolean not null default true,
    trigger_type            varchar(40) not null,
    trigger_expression      varchar(200),
    prevent_concurrent_runs boolean not null default true,
    last_run_started_at     timestamp with time zone,
    last_run_finished_at    timestamp with time zone,
    created_at              timestamp with time zone not null,
    updated_at              timestamp with time zone not null,
    constraint pk_catalog_import_task primary key (id),
    constraint uk_catalog_import_task_name unique (import_link_id, name),
    constraint fk_catalog_import_task_import_link foreign key (import_link_id) references import_link (id),
    constraint ck_catalog_import_task_trigger check (
        trigger_type <> 'SCHEDULED' or trigger_expression is not null
    )
);

-- concurrency_token draagt task_id zolang de run niet in een eindtoestand is en de taak
-- prevent_concurrent_runs = true heeft; anders NULL. De unique constraint dwingt daarmee
-- "hoogstens een lopende run per taak" af op databaseniveau, ook bij gelijktijdige verwerking.
create table task_run (
    id                bigint generated by default as identity,
    task_id           bigint not null,
    status            varchar(40) not null,
    concurrency_token bigint,
    started_at        timestamp with time zone not null,
    finished_at       timestamp with time zone,
    locked_by         varchar(100),
    locked_at         timestamp with time zone,
    triggered_by      varchar(100),
    created_at        timestamp with time zone not null,
    constraint pk_task_run primary key (id),
    constraint uk_task_run_concurrency unique (task_id, concurrency_token),
    constraint fk_task_run_task foreign key (task_id) references catalog_import_task (id)
);

create index idx_task_run_task_started on task_run (task_id, started_at);

-- idempotency_key is de technische registratie-identiteit van een levering (connector, remote
-- object, tijdstempel, run) en NOOIT alleen de inhoudshash: een inhoudelijk identieke
-- herlevering moet een nieuwe Delivery krijgen en volledig gescreend worden.
create table delivery (
    id                    bigint generated by default as identity,
    task_id               bigint not null,
    task_run_id           bigint,
    idempotency_key       varchar(200) not null,
    received_at           timestamp with time zone not null,
    manifest_reference    varchar(500),
    expected_file_count   integer,
    actual_file_count     integer not null default 0,
    expected_record_count bigint,
    actual_record_count   bigint,
    expected_byte_size    bigint,
    actual_byte_size      bigint not null default 0,
    completeness_proven   boolean not null default false,
    supersedes_delivery_id bigint,
    created_at            timestamp with time zone not null,
    constraint pk_delivery primary key (id),
    constraint uk_delivery_idempotency unique (task_id, idempotency_key),
    constraint fk_delivery_task foreign key (task_id) references catalog_import_task (id),
    constraint fk_delivery_task_run foreign key (task_run_id) references task_run (id),
    constraint fk_delivery_supersedes foreign key (supersedes_delivery_id) references delivery (id)
);

create index idx_delivery_task_received on delivery (task_id, received_at);

-- Bewust geen kolom met bestandsinhoud: het bronbestand blijft in objectopslag en de database
-- bewaart enkel archive_reference, hash en grootte als bewijs.
create table delivery_file (
    id                bigint generated by default as identity,
    delivery_id       bigint not null,
    sequence_number   integer not null,
    file_name         varchar(500) not null,
    archive_reference varchar(1000) not null,
    content_hash      varchar(128) not null,
    hash_algorithm    varchar(20) not null default 'SHA-256',
    byte_size         bigint not null,
    received_at       timestamp with time zone not null,
    created_at        timestamp with time zone not null,
    constraint pk_delivery_file primary key (id),
    constraint uk_delivery_file_sequence unique (delivery_id, sequence_number),
    constraint uk_delivery_file_name unique (delivery_id, file_name),
    constraint fk_delivery_file_delivery foreign key (delivery_id) references delivery (id)
);

create index idx_delivery_file_content_hash on delivery_file (content_hash);

--rollback drop table delivery_file;
--rollback drop table delivery;
--rollback drop table task_run;
--rollback drop table catalog_import_task;
--rollback drop table import_link;
--rollback drop table import_definition_revision;
--rollback drop table import_definition;
--rollback drop table source_organisation;
