--liquibase formatted sql

-- Fase 2a (docs/design/fase2-screening-design.md): additief naast 001, die ongewijzigd blijft.
-- ${hash.type} wordt in db.changelog-master.yaml gedefinieerd: bytea (postgresql) / varbinary(32) (h2).

--changeset catalogimport:002-1-revision-source-config
--comment Bronconfiguratie op import_definition_revision (design par. 7). Defaults zijn enkel migratiehulp voor bestaande rijen.

alter table import_definition_revision add column structure_format varchar(20) not null default 'CSV';
alter table import_definition_revision add column structure_charset varchar(40) not null default 'UTF-8';
alter table import_definition_revision add column structure_delimiter varchar(1) not null default ',';
alter table import_definition_revision add column structure_quote_char varchar(1) default '"';
alter table import_definition_revision add column structure_has_header boolean not null default true;
alter table import_definition_revision add column structure_header_line_number integer not null default 1;
alter table import_definition_revision add column structure_field_reference_kind varchar(20) not null default 'HEADER_NAME';
alter table import_definition_revision add column structure_expected_column_count integer;
alter table import_definition_revision add column access_delivery_set_kind varchar(30) not null default 'UNDECLARED';
alter table import_definition_revision add column record_base_price_field varchar(200);
alter table import_definition_revision add column record_description_field varchar(200);
alter table import_definition_revision add column record_canonicalisation_version integer not null default 1;

-- Het scheidingsteken is een bewuste keuze per revisie: de applicatie moet het expliciet zetten.
alter table import_definition_revision alter column structure_delimiter drop default;

alter table import_definition_revision add constraint ck_import_definition_revision_format
    check (structure_format in ('CSV'));
alter table import_definition_revision add constraint ck_import_definition_revision_field_reference
    check (structure_field_reference_kind in ('HEADER_NAME', 'COLUMN_INDEX'));
alter table import_definition_revision add constraint ck_import_definition_revision_delivery_set
    check (access_delivery_set_kind in ('FULL_SNAPSHOT', 'DELTA', 'UNDECLARED'));
alter table import_definition_revision add constraint ck_import_definition_revision_header_reference
    check (structure_has_header or structure_field_reference_kind = 'COLUMN_INDEX');

--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_header_reference;
--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_delivery_set;
--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_field_reference;
--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_format;
--rollback alter table import_definition_revision drop column record_canonicalisation_version;
--rollback alter table import_definition_revision drop column record_description_field;
--rollback alter table import_definition_revision drop column record_base_price_field;
--rollback alter table import_definition_revision drop column access_delivery_set_kind;
--rollback alter table import_definition_revision drop column structure_expected_column_count;
--rollback alter table import_definition_revision drop column structure_field_reference_kind;
--rollback alter table import_definition_revision drop column structure_header_line_number;
--rollback alter table import_definition_revision drop column structure_has_header;
--rollback alter table import_definition_revision drop column structure_quote_char;
--rollback alter table import_definition_revision drop column structure_delimiter;
--rollback alter table import_definition_revision drop column structure_charset;
--rollback alter table import_definition_revision drop column structure_format;

--changeset catalogimport:002-2-import-batch
--comment Eén screening van één levering onder één bevroren revisie (design par. 1).

-- open_marker is TRUE zolang de batch niet-terminaal is en NULL in SCREENED/BLOCKED/FAILED/BASELINE_ACCEPTED.
-- NULL-waarden botsen niet in een UNIQUE constraint: hoogstens een open batch per levering, op databaseniveau.
-- Tellers zijn nullable: NULL = onbekend, nooit stil 0.
create table import_batch (
    id                          bigint generated by default as identity,
    delivery_id                 bigint not null,
    import_link_id              bigint not null,
    definition_revision_id      bigint not null,
    task_run_id                 bigint,
    attempt_no                  integer not null default 1,
    status                      varchar(40) not null,
    open_marker                 boolean,
    started_at                  timestamp with time zone,
    finished_at                 timestamp with time zone,
    staged_row_count            bigint not null default 0,
    mutation_progress_row_number bigint not null default 0,
    raw_record_count            bigint,
    valid_record_count          bigint,
    rejected_record_count       bigint,
    duplicate_identity_count    bigint,
    new_count                   bigint,
    changed_count               bigint,
    unchanged_count             bigint,
    content_mutation_count      bigint,
    blocked_code                varchar(60),
    blocked_reason              varchar(500),
    created_at                  timestamp with time zone not null,
    created_by                  varchar(100),
    constraint pk_import_batch primary key (id),
    constraint uk_import_batch_attempt unique (delivery_id, definition_revision_id, attempt_no),
    constraint uk_import_batch_open unique (delivery_id, open_marker),
    constraint fk_import_batch_delivery foreign key (delivery_id) references delivery (id),
    constraint fk_import_batch_import_link foreign key (import_link_id) references import_link (id),
    constraint fk_import_batch_definition_revision foreign key (definition_revision_id) references import_definition_revision (id),
    constraint fk_import_batch_task_run foreign key (task_run_id) references task_run (id)
);

create index idx_import_batch_link_created on import_batch (import_link_id, created_at);

--rollback drop table import_batch;

--changeset catalogimport:002-3-import-candidate-stage
--comment Staging van gevalideerde kandidaten per batch (design par. 2). JDBC-only, geen entiteit; nooit ruwe brontekst.

create table import_candidate_stage (
    batch_id                       bigint not null,
    row_number                     bigint not null,
    delivery_file_id               bigint not null,
    identity_supplier              varchar(200) not null,
    identity_supplier_group        varchar(200) not null,
    identity_supplier_reference    varchar(200) not null,
    identity_discount_code         varchar(200),
    identity_discount_state        varchar(20) not null,
    identity_hash                  ${hash.type} not null,
    base_price                     numeric(24,6) not null,
    base_price_currency            varchar(3),
    description                    varchar(1000),
    article_fingerprint            ${hash.type} not null,
    price_fingerprint              ${hash.type} not null,
    combined_fingerprint           ${hash.type} not null,
    mutation_key_prefix            varchar(160) not null,
    classification                 varchar(30),
    created_at                     timestamp with time zone not null,
    constraint pk_import_candidate_stage primary key (batch_id, row_number),
    constraint fk_import_candidate_stage_batch foreign key (batch_id) references import_batch (id),
    constraint fk_import_candidate_stage_file foreign key (delivery_file_id) references delivery_file (id)
);

-- Bewust NIET unique: een dubbele identiteit in een levering moet gestaged en daarna gemeld kunnen worden.
create index idx_import_candidate_stage_identity on import_candidate_stage (batch_id, identity_hash);
create index idx_import_candidate_stage_classification on import_candidate_stage (batch_id, classification);

--rollback drop table import_candidate_stage;

--changeset catalogimport:002-4-import-row-issue
--comment Gerapporteerde problemen per bronregel (design par. 5).

create table import_row_issue (
    id               bigint generated by default as identity,
    batch_id         bigint not null,
    delivery_file_id bigint not null,
    row_number       bigint not null,
    issue_code       varchar(60) not null,
    field_name       varchar(200),
    severity         varchar(20) not null default 'ERROR',
    source_value     varchar(200),
    message          varchar(500) not null,
    created_at       timestamp with time zone not null,
    constraint pk_import_row_issue primary key (id),
    constraint fk_import_row_issue_batch foreign key (batch_id) references import_batch (id),
    constraint fk_import_row_issue_file foreign key (delivery_file_id) references delivery_file (id)
);

create index idx_import_row_issue_batch_code on import_row_issue (batch_id, issue_code);

--rollback drop table import_row_issue;

--changeset catalogimport:002-5-catalog-source-state
--comment Laatst aanvaarde bronstaat per aanbiedingsidentiteit binnen een importkoppeling (design par. 3). JDBC-only.

create table catalog_source_state (
    id                           bigint generated by default as identity,
    import_link_id               bigint not null,
    identity_hash                ${hash.type} not null,
    identity_supplier            varchar(200) not null,
    identity_supplier_group      varchar(200) not null,
    identity_supplier_reference  varchar(200) not null,
    identity_discount_code       varchar(200),
    identity_discount_state      varchar(20) not null,
    identity_profile_kind        varchar(40) not null,
    article_fingerprint          ${hash.type} not null,
    price_fingerprint            ${hash.type} not null,
    combined_fingerprint         ${hash.type} not null,
    base_price                   numeric(24,6) not null,
    base_price_currency          varchar(3),
    state_origin                 varchar(30) not null,
    last_change_delivery_id      bigint not null,
    last_change_batch_id         bigint not null,
    active                       boolean not null default true,
    accepted_by                  varchar(100),
    accepted_at                  timestamp with time zone,
    created_at                   timestamp with time zone not null,
    updated_at                   timestamp with time zone not null,
    constraint pk_catalog_source_state primary key (id),
    constraint uk_catalog_source_state_identity unique (import_link_id, identity_hash),
    constraint fk_catalog_source_state_import_link foreign key (import_link_id) references import_link (id),
    constraint fk_catalog_source_state_delivery foreign key (last_change_delivery_id) references delivery (id),
    constraint fk_catalog_source_state_batch foreign key (last_change_batch_id) references import_batch (id)
);

--rollback drop table catalog_source_state;

--changeset catalogimport:002-6-import-mutation
--comment Centrale mutatielijst (PSIMPORT001) per batch, met idempotentiesleutel en IMPORT_MARKER (design par. 4).

create table import_mutation (
    id                          bigint generated by default as identity,
    batch_id                    bigint not null,
    delivery_id                 bigint not null,
    import_link_id              bigint not null,
    definition_revision_id      bigint not null,
    task_run_id                 bigint,
    action_type                 varchar(20) not null,
    target_domain               varchar(20) not null,
    status                      varchar(40) not null,
    status_reason               varchar(200),
    identity_supplier           varchar(200),
    identity_supplier_group     varchar(200),
    identity_supplier_reference varchar(200),
    identity_discount_code      varchar(200),
    identity_discount_state     varchar(20),
    identity_hash               ${hash.type},
    before_combined_fingerprint ${hash.type},
    after_combined_fingerprint  ${hash.type},
    domain_mask                 varchar(100),
    before_base_price           numeric(24,6),
    after_base_price            numeric(24,6),
    base_price_currency         varchar(3),
    source_state_id             bigint,
    delivery_file_id            bigint,
    source_row_number           bigint,
    result_summary              varchar(1000),
    idempotency_key             varchar(200) not null,
    created_at                  timestamp with time zone not null,
    constraint pk_import_mutation primary key (id),
    constraint uk_import_mutation_idempotency unique (idempotency_key),
    constraint fk_import_mutation_batch foreign key (batch_id) references import_batch (id),
    constraint fk_import_mutation_delivery foreign key (delivery_id) references delivery (id),
    constraint fk_import_mutation_import_link foreign key (import_link_id) references import_link (id),
    constraint fk_import_mutation_definition_revision foreign key (definition_revision_id) references import_definition_revision (id),
    constraint fk_import_mutation_task_run foreign key (task_run_id) references task_run (id),
    constraint fk_import_mutation_source_state foreign key (source_state_id) references catalog_source_state (id),
    constraint fk_import_mutation_file foreign key (delivery_file_id) references delivery_file (id),
    constraint ck_import_mutation_marker check (
        (action_type = 'IMPORT_MARKER'
            and target_domain = 'IMPORT'
            and status = 'RECORDED'
            and identity_supplier is null
            and identity_supplier_group is null
            and identity_supplier_reference is null
            and identity_hash is null)
        or (action_type in ('CREATE', 'UPDATE')
            and target_domain <> 'IMPORT'
            and identity_supplier is not null
            and identity_supplier_group is not null
            and identity_supplier_reference is not null)
    )
);

create index idx_import_mutation_batch_status on import_mutation (batch_id, status);
create index idx_import_mutation_link_identity on import_mutation (import_link_id, identity_hash);

--rollback drop table import_mutation;
