--liquibase formatted sql

-- Fase 3 (docs/design/fase3-rules-design.md par. 2): additief naast 001, 002 en 003, die ongewijzigd blijven.
-- Bouwstap 3a levert enkel de sub-changesets die het issuemodel nodig heeft: 004-4, 004-11 (basisdeel) en
-- 004-12. Bouwstap 3b voegt 004-1 (+ seed 004-1b), 004-2, 004-3, 004-10 en 004-11b toe. De overige
-- sub-changesets uit par. 2 (004-5..9, 004-13, 004-14) worden door de volgende bouwstappen additief
-- aan dit bestand toegevoegd, met hun eigen id.
--
-- Een reeds uitgevoerde changeset wordt nooit bijgewerkt (checksum): de resterende kolommen van 004-11
-- (tellers en voortgangskolommen van de passes E1-E4) krijgen daarom in bouwstap 3b-3h een eigen id
-- 004-11b, niet een uitbreiding van 004-11 hieronder.

--changeset catalogimport:004-4-import-issue-group
--comment Samenvatting per foutsignatuur binnen een batch (ontwerp fase 3 par. 2, R-ISS-03/R-THR-04). De tabel wordt in bouwstap 3a enkel aangemaakt; vullen en bulkincidenten zijn bouwstap 3g.

-- occurrence_count is het VOLLEDIGE aantal voorvallen, recorded_sample_count het aantal bewaarde
-- voorbeeldrijen in import_row_issue. Die twee lopen bewust uiteen: bij een miljoen identieke fouten
-- worden er hoogstens N voorbeelden bewaard, maar het totaal mag nooit verloren gaan.
create table import_issue_group (
    id                   bigint generated by default as identity,
    batch_id             bigint not null,
    issue_code           varchar(60) not null,
    signature            varchar(300) not null,
    severity             varchar(20) not null,
    issue_domain         varchar(40) not null,
    control_level        varchar(20) not null,
    impact_scope         varchar(20) not null,
    incident_kind        varchar(30) not null default 'GENERIC',
    occurrence_count     bigint not null,
    recorded_sample_count integer not null,
    scope_record_count   bigint,
    share_percent        numeric(24,12),
    is_bulk_incident     boolean not null default false,
    price_component_code varchar(20),
    deviation_direction  varchar(10),
    dominant_factor      numeric(24,12),
    reference_type       varchar(30),
    pattern_description  varchar(500),
    first_row_number     bigint,
    first_detected_at    timestamp with time zone,
    last_detected_at     timestamp with time zone,
    handling_status      varchar(30) not null default 'DETECTED',
    constraint pk_import_issue_group primary key (id),
    constraint uk_import_issue_group_signature unique (batch_id, issue_code, signature),
    constraint fk_import_issue_group_batch foreign key (batch_id) references import_batch (id),
    constraint ck_import_issue_group_incident_kind
        check (incident_kind in ('GENERIC', 'PRICE', 'IDENTITY', 'CREATION'))
);

create index idx_import_issue_group_batch_severity on import_issue_group (batch_id, severity);

--rollback drop table import_issue_group;

--changeset catalogimport:004-11-import-batch-validation-result
--comment Inhoudelijk eindoordeel als aparte statusas naast status (ontwerp fase 3 par. 0 afwijking D, R-THR-06).

-- Nullable: NULL betekent "nog niet vastgesteld" (lopende batch) of "niets vast te stellen"
-- (technische fout, FAILED). Nooit stil VALID. De overige 004-11-kolommen (tellers, voortgang per
-- pass) volgen in een latere bouwstap onder id 004-11b.
alter table import_batch add column validation_result varchar(30);

--rollback alter table import_batch drop column validation_result;

--changeset catalogimport:004-12-import-row-issue-control-model
--comment import_row_issue draagt voortaan alle drie de controleniveaus (ontwerp fase 3 par. 2 004-12, par. 3.3).

-- De tabel wordt UITGEBREID, niet vervangen of hernoemd (aanname A14): geen datamigratie, en de
-- fase 2-contracten blijven werken. De defaults zijn zo gekozen dat elke bestaande rij - allemaal
-- regelproblemen uit fase 2 - geldig blijft zonder update-statement.
--
-- row_number en delivery_file_id worden nullable: een probleem op leverings- of structuurniveau
-- (leeg bestand, ontbrekende headerkolom, configuratiefout) hoort bij geen enkele bronregel. Een
-- verzonnen regelnummer 0 zou dat verschil verbergen.
alter table import_row_issue alter column row_number drop not null;
alter table import_row_issue alter column delivery_file_id drop not null;

alter table import_row_issue add column issue_domain varchar(40) not null default 'MAPPING_VALIDATION';
alter table import_row_issue add column control_level varchar(20) not null default 'RECORD';
alter table import_row_issue add column impact_scope varchar(20) not null default 'RECORD';
alter table import_row_issue add column issue_group_id bigint;
alter table import_row_issue add column handling_status varchar(30) not null default 'DETECTED';
alter table import_row_issue add column rule_config_version integer;
alter table import_row_issue add column expected_value varchar(200);
alter table import_row_issue add column occurrence_seq integer;

alter table import_row_issue add constraint fk_import_row_issue_group
    foreign key (issue_group_id) references import_issue_group (id);

create index idx_import_row_issue_batch_severity on import_row_issue (batch_id, severity);
create index idx_import_row_issue_group on import_row_issue (issue_group_id);

--rollback drop index idx_import_row_issue_group;
--rollback drop index idx_import_row_issue_batch_severity;
--rollback alter table import_row_issue drop constraint fk_import_row_issue_group;
--rollback alter table import_row_issue drop column occurrence_seq;
--rollback alter table import_row_issue drop column expected_value;
--rollback alter table import_row_issue drop column rule_config_version;
--rollback alter table import_row_issue drop column handling_status;
--rollback alter table import_row_issue drop column issue_group_id;
--rollback alter table import_row_issue drop column impact_scope;
--rollback alter table import_row_issue drop column control_level;
--rollback alter table import_row_issue drop column issue_domain;
--rollback alter table import_row_issue alter column delivery_file_id set not null;
--rollback alter table import_row_issue alter column row_number set not null;

-- =============================================================================================
-- Bouwstap 3b: veldcatalogus, veldmapping, recordfilters en de bijhorende revisie-/batchkolommen
-- (ontwerp fase 3 par. 2 sub-changesets 004-1, 004-2, 004-3, 004-10 en het 3b-deel van 004-11).
-- De hierboven reeds uitgevoerde changesets 004-4, 004-11 en 004-12 blijven ongewijzigd.
-- =============================================================================================

--changeset catalogimport:004-1-import-field-catalog
--comment Logische doelvelden die een importdefinitie mag vullen (ontwerp fase 3 par. 2 004-1, R-STR-04/R-STR-05/R-REF-08).

-- Referentiedata, geen configuratie per revisie: welke doelvelden er bestaan, wie er eigenaar van is
-- en welk gewicht ze in de identiteit hebben. Een mapping verwijst hiernaar; de revisie kan de
-- eigenaar enkel wijzigen zolang owner_changeable dat toelaat (R-REF-08).
--
-- identity_class NONE betekent "speelt geen rol in de identiteit". Prijs en omschrijving staan
-- bewust op NONE: die mogen nooit identiteitsbeslissend zijn (R-ID-08).
create table import_field_catalog (
    code                 varchar(60) not null,
    name                 varchar(200) not null,
    data_type            varchar(20) not null,
    default_owner        varchar(30) not null,
    identity_class       varchar(30) not null,
    price_component_code varchar(20),
    reference_type       varchar(30),
    owner_changeable     boolean not null default true,
    target_route         varchar(200),
    sort_order           integer not null,
    active               boolean not null default true,
    constraint pk_import_field_catalog primary key (code),
    constraint ck_import_field_catalog_data_type
        check (data_type in ('TEXT', 'DECIMAL', 'INTEGER', 'DATE', 'DATETIME', 'BOOLEAN')),
    constraint ck_import_field_catalog_owner
        check (default_owner in ('CATALOG_SOURCE', 'PRICE_CONTROL', 'CRITICAL_REFERENCE', 'PRODIS_USER')),
    constraint ck_import_field_catalog_identity_class
        check (identity_class in ('STRONG', 'ARTICLE_REFERENCE', 'SUPPORTING', 'WEAK', 'NONE')),
    constraint ck_import_field_catalog_price_component
        check (price_component_code is null or default_owner = 'PRICE_CONTROL'),
    -- Een kritieke referentie is per definitie eigendom van de referentiecontrole en die eigenaar is
    -- niet wisselbaar: anders zou een revisie de EAN-controle stil kunnen uitschakelen (R-REF-08).
    constraint ck_import_field_catalog_reference
        check (reference_type is null or (default_owner = 'CRITICAL_REFERENCE' and owner_changeable = false))
);

--rollback drop table import_field_catalog;

--changeset catalogimport:004-1b-import-field-catalog-seed
--comment Seed van de veldcatalogus (ontwerp fase 3 par. 2 004-1). BRAND en UNIT zijn eigendom van de Prodis-gebruiker en niet door een import te overschrijven.

insert into import_field_catalog (code, name, data_type, default_owner, identity_class,
        price_component_code, reference_type, owner_changeable, target_route, sort_order, active) values
    ('BASE_PRICE', 'Basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'BASE_PRICE', null, true, 'offer.price.base', 10, true),
    ('AKP_PCT', 'Aankoopprijs in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'AKP', null, true, 'offer.price.akp', 20, true),
    ('VKP1_PCT', 'Verkoopprijs 1 in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP1', null, true, 'offer.price.vkp1', 30, true),
    ('VKP2_PCT', 'Verkoopprijs 2 in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP2', null, true, 'offer.price.vkp2', 40, true),
    ('VKP3_PCT', 'Verkoopprijs 3 in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP3', null, true, 'offer.price.vkp3', 50, true),
    ('VKP4_PCT', 'Verkoopprijs 4 in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP4', null, true, 'offer.price.vkp4', 60, true),
    ('VKP5_PCT', 'Verkoopprijs 5 in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP5', null, true, 'offer.price.vkp5', 70, true),
    ('VKP_GROSS_PCT', 'Brutoverkoopprijs in procent van de basisprijs', 'DECIMAL', 'PRICE_CONTROL', 'NONE', 'VKP_GROSS', null, true, 'offer.price.vkpGross', 80, true),
    ('EAN', 'EAN-barcode', 'TEXT', 'CRITICAL_REFERENCE', 'ARTICLE_REFERENCE', null, 'EAN', false, 'article.reference.ean', 90, true),
    ('PIM_ID', 'PIM-identiteit', 'TEXT', 'CRITICAL_REFERENCE', 'ARTICLE_REFERENCE', null, 'PIM_ID', false, 'article.reference.pimId', 100, true),
    ('CAB_ID', 'CAB-identiteit', 'TEXT', 'CRITICAL_REFERENCE', 'ARTICLE_REFERENCE', null, 'CAB_ID', false, 'article.reference.cabId', 110, true),
    ('E_MARK_ARTICLE_REFERENCE', 'E-merk met artikelreferentie', 'TEXT', 'CRITICAL_REFERENCE', 'ARTICLE_REFERENCE', null, 'E_MARK_ARTICLE_REFERENCE', false, 'article.reference.eMark', 120, true),
    ('E_SUPPLIER', 'Externe leveranciersidentiteit', 'TEXT', 'CATALOG_SOURCE', 'SUPPORTING', null, null, true, 'offer.externalSupplier', 130, true),
    ('SUPPLIER_BARCODE', 'Leveranciersbarcode', 'TEXT', 'CATALOG_SOURCE', 'SUPPORTING', null, null, true, 'offer.supplierBarcode', 140, true),
    ('DESCRIPTION', 'Omschrijving', 'TEXT', 'CATALOG_SOURCE', 'NONE', null, null, true, 'article.description', 150, true),
    ('BRAND', 'Merk', 'TEXT', 'PRODIS_USER', 'NONE', null, null, false, 'article.brand', 160, true),
    ('UNIT', 'Eenheid', 'TEXT', 'PRODIS_USER', 'NONE', null, null, false, 'article.unit', 170, true);

--rollback delete from import_field_catalog;

--changeset catalogimport:004-2-import-field-mapping
--comment Mapping van bronveld naar doelveld per bevroren revisie (ontwerp fase 3 par. 2 004-2, R-STR-04).

-- source_reference draagt - net als identity_*_field op de revisie - ofwel een headernaam ofwel een
-- 1-gebaseerde kolomindex, afhankelijk van structure_field_reference_kind.
--
-- expected_position is de kolompositie waarop dit veld bij het vastleggen van de revisie stond. Ze is
-- optioneel en dient enkel voor de headerpositiecontrole (R-STR-02/R-STR-03): de headernaam blijft
-- leidend, een verschoven kolom is een waarschuwing en geen stille hermapping.
--
-- Sjablonen/bookmarks (par. 14.16 van de businessanalyse, beslissingslog 18/09) kunnen later zonder
-- migratie aansluiten: value_kind BOOKMARK en bookmark_name bestaan al; er komen dan enkel tabellen
-- bij, deze tabel blijft ongewijzigd.
create table import_field_mapping (
    id                     bigint generated by default as identity,
    definition_revision_id bigint not null,
    sequence_number        integer not null,
    target_field_code      varchar(60) not null,
    value_kind             varchar(20) not null,
    source_reference       varchar(200),
    expected_position      integer,
    fixed_value            varchar(500),
    bookmark_name          varchar(60),
    default_value          varchar(500),
    data_type              varchar(20) not null,
    required               boolean not null default false,
    max_length             integer,
    decimal_scale          integer,
    zero_allowed           boolean not null default false,
    negative_allowed       boolean not null default false,
    transform_kind         varchar(30) not null default 'NONE',
    transform_config       varchar(1000),
    field_owner            varchar(30) not null,
    identity_class         varchar(30) not null,
    price_component_code   varchar(20),
    reference_type         varchar(30),
    active                 boolean not null default true,
    created_at             timestamp with time zone not null,
    created_by             varchar(100),
    constraint pk_import_field_mapping primary key (id),
    constraint uk_import_field_mapping_target unique (definition_revision_id, target_field_code),
    constraint uk_import_field_mapping_sequence unique (definition_revision_id, sequence_number),
    constraint fk_import_field_mapping_revision foreign key (definition_revision_id)
        references import_definition_revision (id),
    constraint fk_import_field_mapping_target foreign key (target_field_code)
        references import_field_catalog (code),
    constraint ck_import_field_mapping_value_kind
        check (value_kind in ('SOURCE_FIELD', 'FIXED_VALUE', 'BOOKMARK', 'DERIVED')),
    constraint ck_import_field_mapping_source
        check (value_kind <> 'SOURCE_FIELD' or source_reference is not null),
    constraint ck_import_field_mapping_fixed
        check (value_kind <> 'FIXED_VALUE' or fixed_value is not null),
    constraint ck_import_field_mapping_bookmark
        check (value_kind <> 'BOOKMARK' or bookmark_name is not null),
    constraint ck_import_field_mapping_data_type
        check (data_type in ('TEXT', 'DECIMAL', 'INTEGER', 'DATE', 'DATETIME', 'BOOLEAN')),
    constraint ck_import_field_mapping_owner
        check (field_owner in ('CATALOG_SOURCE', 'PRICE_CONTROL', 'CRITICAL_REFERENCE', 'PRODIS_USER')),
    constraint ck_import_field_mapping_identity_class
        check (identity_class in ('STRONG', 'ARTICLE_REFERENCE', 'SUPPORTING', 'WEAK', 'NONE')),
    constraint ck_import_field_mapping_price_component
        check (price_component_code is null or field_owner = 'PRICE_CONTROL'),
    constraint ck_import_field_mapping_reference
        check (reference_type is null or field_owner = 'CRITICAL_REFERENCE')
);

create index idx_import_field_mapping_revision on import_field_mapping (definition_revision_id, sequence_number);

--rollback drop table import_field_mapping;

--changeset catalogimport:004-3-import-record-filter
--comment Recordfilters die de importscope bepalen (ontwerp fase 3 par. 2 004-3, R-FLT-01..R-FLT-03).

-- Het filter is onderdeel van de importscope, niet een schermfilter: het bepaalt waarop de
-- creatiedrempel, de duplicaatcontrole en later het volledigheidsbewijs rekenen (par. 14.4).
--
-- null_behaviour bepaalt wat een ontbrekende of lege bronwaarde betekent; missing_column_behaviour
-- wat een ontbrekende kolom betekent. Geen van beide mag ooit stil "het filter matcht niet" worden
-- (R-FLT-03): de standaard is uitsluiten respectievelijk de levering blokkeren.
--
-- created_at/created_by staan niet in het ontwerp maar zijn hier toegevoegd omdat een filterwijziging
-- de importscope wijzigt: zonder die twee kolommen is achteraf niet meer vast te stellen wanneer en
-- door wie de scope van een levering veranderd is.
create table import_record_filter (
    id                       bigint generated by default as identity,
    definition_revision_id   bigint not null,
    sequence_number          integer not null,
    filter_stage             varchar(20) not null default 'SOURCE_FIELD',
    source_reference         varchar(200) not null,
    operator                 varchar(20) not null,
    compare_value            varchar(500) not null,
    outcome                  varchar(20) not null,
    case_sensitive           boolean not null default false,
    trim_before_compare      boolean not null default true,
    null_behaviour           varchar(20) not null default 'EXCLUDE',
    missing_column_behaviour varchar(20) not null default 'BLOCK',
    created_at               timestamp with time zone,
    created_by               varchar(100),
    constraint pk_import_record_filter primary key (id),
    constraint uk_import_record_filter_sequence unique (definition_revision_id, sequence_number),
    constraint fk_import_record_filter_revision foreign key (definition_revision_id)
        references import_definition_revision (id),
    constraint ck_import_record_filter_stage
        check (filter_stage in ('SOURCE_FIELD', 'TARGET_FIELD')),
    constraint ck_import_record_filter_operator
        check (operator in ('EQUALS', 'NOT_EQUALS', 'BEGINS_WITH', 'ENDS_WITH', 'CONTAINS', 'NOT_CONTAINS')),
    constraint ck_import_record_filter_outcome
        check (outcome in ('INCLUDE', 'EXCLUDE', 'REJECT')),
    constraint ck_import_record_filter_null_behaviour
        check (null_behaviour in ('EXCLUDE', 'REJECT', 'COMPARE_AS_EMPTY')),
    constraint ck_import_record_filter_missing_column
        check (missing_column_behaviour in ('BLOCK', 'EXCLUDE', 'REJECT'))
);

--rollback drop table import_record_filter;

--changeset catalogimport:004-10-import-definition-revision-rules
--comment Prijs-, drempel- en valutabeleid per revisie (ontwerp fase 3 par. 2 004-10). Additief; de defaults zijn de normatieve waarden uit het ontwerp.

-- De defaults gelden ook voor bestaande revisies: 15% afwijkingsgrens (R-PRI-10), tolerantie 0,01 op
-- de prijsreconstructie (R-PRI-07), vensters van 50 en 200 dagwaarden (R-PRI-10), creatiedrempel
-- 100 nieuwe aanbiedingen EN 1% van de importscope (R-THR-01; NIET 100%) en max_critical_records 0
-- (R-THR-05: één kritiek record blokkeert de levering tenzij expliciet anders ingesteld).
-- max_rejected_records en max_rejected_share_percent hebben bewust GEEN default: NULL betekent
-- "niet geconfigureerd", niet "0".
alter table import_definition_revision add column price_deviation_percent numeric(24,12) not null default 15;
alter table import_definition_revision add column price_deviation_severity varchar(20) not null default 'WARNING';
alter table import_definition_revision add column price_derivation_tolerance numeric(24,6) not null default 0.01;
alter table import_definition_revision add column price_avg_short_window integer not null default 50;
alter table import_definition_revision add column price_avg_long_window integer not null default 200;
alter table import_definition_revision add column price_control_model varchar(20) not null default 'DEVIATION';
alter table import_definition_revision add column creation_threshold_absolute integer not null default 100;
alter table import_definition_revision add column creation_threshold_share_percent numeric(24,12) not null default 1;
alter table import_definition_revision add column max_critical_records integer not null default 0;
alter table import_definition_revision add column max_rejected_records integer;
alter table import_definition_revision add column max_rejected_share_percent numeric(24,12);
alter table import_definition_revision add column record_currency_field varchar(200);

alter table import_definition_revision add constraint ck_import_definition_revision_price_model
    check (price_control_model in ('DEVIATION', 'BOXPLOT'));
alter table import_definition_revision add constraint ck_import_definition_revision_deviation_severity
    check (price_deviation_severity in ('WARNING', 'ERROR'));

--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_deviation_severity;
--rollback alter table import_definition_revision drop constraint ck_import_definition_revision_price_model;
--rollback alter table import_definition_revision drop column record_currency_field;
--rollback alter table import_definition_revision drop column max_rejected_share_percent;
--rollback alter table import_definition_revision drop column max_rejected_records;
--rollback alter table import_definition_revision drop column max_critical_records;
--rollback alter table import_definition_revision drop column creation_threshold_share_percent;
--rollback alter table import_definition_revision drop column creation_threshold_absolute;
--rollback alter table import_definition_revision drop column price_control_model;
--rollback alter table import_definition_revision drop column price_avg_long_window;
--rollback alter table import_definition_revision drop column price_avg_short_window;
--rollback alter table import_definition_revision drop column price_derivation_tolerance;
--rollback alter table import_definition_revision drop column price_deviation_severity;
--rollback alter table import_definition_revision drop column price_deviation_percent;

--changeset catalogimport:004-11b-import-batch-filter-counters
--comment De twee tellers die de recordfilterstap nodig heeft (ontwerp fase 3 par. 2 004-11, R-FLT-04).

-- Nullable: NULL betekent onbekend (het bestand is niet volledig gelezen), nooit stil 0. Samen met de
-- bestaande tellers moet gelden: raw = filtered_out + error_before_filter + rejected + valid.
-- De overige 004-11-kolommen (incidenttellers, voortgang per pass, baseline_approved_by) volgen in
-- bouwstap 3c-3h onder een eigen id; een uitgevoerde changeset wordt nooit bijgewerkt.
alter table import_batch add column filtered_out_count bigint;
alter table import_batch add column error_before_filter_count bigint;

--rollback alter table import_batch drop column error_before_filter_count;
--rollback alter table import_batch drop column filtered_out_count;

-- =============================================================================================
-- Bouwstap 3c: de referentiedeelvingerafdruk van canonicalisatieversie 2 (ontwerp fase 3 par. 2
-- sub-changeset 004-14 en par. 3.5). De reeds uitgevoerde changesets hierboven blijven ongewijzigd.
-- =============================================================================================

--changeset catalogimport:004-14-catalog-source-state-reference-fingerprint
--comment Deelvingerafdruk over de kritieke referenties van een aanbieding (ontwerp fase 3 par. 2 004-14, par. 3.5).

-- Nullable, en dat blijft zo: een revisie op canonicalisatieversie 1 kent geen referentiedeel. NULL
-- betekent hier "deze bronstaat is onder versie 1 vastgelegd", niet "geen referenties" - die twee
-- mogen nooit door elkaar lopen, want versie 2 schrijft voor een aanbieding zonder referenties wél
-- een (lege) vingerafdruk.
alter table catalog_source_state add column reference_fingerprint ${hash.type};

--rollback alter table catalog_source_state drop column reference_fingerprint;

--changeset catalogimport:004-14b-import-candidate-stage-reference-fingerprint
--comment Dezelfde deelvingerafdruk op de staging, zodat de gecombineerde hash reproduceerbaar blijft.

-- Zonder deze kolom zou accept-baseline de referentievingerafdruk van een kandidaat niet naar de
-- bronstaat kunnen overnemen en zou combined_fingerprint achteraf niet meer uit zijn vier delen te
-- herleiden zijn. Nullable om dezelfde reden als hierboven: versie 1 vult ze niet.
alter table import_candidate_stage add column reference_fingerprint ${hash.type};

--rollback alter table import_candidate_stage drop column reference_fingerprint;

-- =============================================================================================
-- Bouwstap 3d: prijscomponenten en percentages (ontwerp fase 3 par. 2 sub-changesets 004-5 en
-- 004-6, par. 3.4 rekenregels, R-PRI-02..R-PRI-09 en R-PRI-15). De reeds uitgevoerde changesets
-- hierboven blijven ongewijzigd.
--
-- FINANCIEEL: bedragen zijn numeric(24,6) en percentages numeric(24,12) - nooit een drijvendekomma-
-- type. Een bedrag dat niet gelezen kan worden komt hier niet terecht (die bronregel wordt verworpen);
-- er bestaat dus geen rij met een stil ingevulde 0.
-- =============================================================================================

--changeset catalogimport:004-5-import-candidate-price
--comment Prijscomponenten van één gestagede kandidaat (ontwerp fase 3 par. 2 004-5, R-PRI-04/R-PRI-05).

-- JDBC-only, net als import_candidate_stage: een levering kan een miljoen regels met tot zeven
-- componenten bevatten. De sleutel is (batch_id, row_number, component_code) - geen gegenereerde id -
-- zodat een hervatte microbatch nooit een tweede rij voor dezelfde component kan schrijven.
--
-- De basisprijs krijgt bewust een eigen rij met component_code 'BASE_PRICE': zonder die rij is een
-- percentage achteraf niet meer te reconstrueren (R-PRI-07) omdat import_candidate_stage.base_price
-- een levend gegeven van de kandidaat is. percentage blijft daar NULL - de basisprijs is 100% van
-- zichzelf en dat getal zou enkel verwarring stichten.
--
-- on delete cascade: de staging is één geheel. Bij een technisch mislukte poging wordt de staging
-- opgeruimd (design fase 2 par. 9 stap C); haar prijscomponenten mogen dan niet als wees achterblijven
-- en de opruiming mag niet van de volgorde in de Java-code afhangen.
create table import_candidate_price (
    batch_id       bigint not null,
    row_number     bigint not null,
    component_code varchar(20) not null,
    source_amount  numeric(24,6),
    percentage     numeric(24,12),
    currency       varchar(3),
    status         varchar(30) not null,
    constraint pk_import_candidate_price primary key (batch_id, row_number, component_code),
    constraint fk_import_candidate_price_stage foreign key (batch_id, row_number)
        references import_candidate_stage (batch_id, row_number) on delete cascade,
    -- De basisprijs draagt altijd een bedrag en nooit een percentage.
    constraint ck_import_candidate_price_base
        check (component_code <> 'BASE_PRICE' or (percentage is null and source_amount is not null)),
    -- Een afgeleide component zonder percentage moet zeggen waarom: status <> 'OK' (bv. NO_BASE_PRICE).
    -- Zo kan er nooit een component bestaan die stilzwijgend "geen verhouding" betekent.
    constraint ck_import_candidate_price_component
        check (component_code = 'BASE_PRICE' or percentage is not null or status <> 'OK')
);

create index idx_import_candidate_price_component on import_candidate_price (batch_id, component_code);

--rollback drop table import_candidate_price;

--changeset catalogimport:004-6-catalog-source-state-price
--comment Aanvaarde prijscomponenten per bronstaat (ontwerp fase 3 par. 2 004-6, R-PRI-09).

-- Dit is de "voor"-waarde waartegen de volgende levering vergeleken wordt: zonder deze tabel zou een
-- percentagewijziging bij een ongewijzigde basisprijs onzichtbaar blijven in de delta (R-PRI-09).
-- Enkel accept-baseline (en later de publicatie) schrijft hier; de screening nooit.
--
-- updated_at staat per component: een levering die enkel de aankoopprijs wijzigt, mag de tijdstempel
-- van de andere componenten niet verzetten.
create table catalog_source_state_price (
    source_state_id bigint not null,
    component_code  varchar(20) not null,
    amount          numeric(24,6),
    percentage      numeric(24,12),
    currency        varchar(3),
    updated_at      timestamp with time zone not null,
    constraint pk_catalog_source_state_price primary key (source_state_id, component_code),
    constraint fk_catalog_source_state_price_state foreign key (source_state_id)
        references catalog_source_state (id),
    constraint ck_catalog_source_state_price_base
        check (component_code <> 'BASE_PRICE' or (percentage is null and amount is not null)),
    -- Strenger dan de staging: in de aanvaarde bronstaat bestaat geen component zonder verhouding.
    -- Een component die niet berekend kon worden, wordt nooit aanvaard.
    constraint ck_catalog_source_state_price_component
        check (component_code = 'BASE_PRICE' or percentage is not null)
);

--rollback drop table catalog_source_state_price;

--changeset catalogimport:004-10b-import-definition-revision-base-price-flags
--comment Nul- en negatiefbeleid van de basisprijs per revisie (R-PRI-02/R-PRI-03).

-- Een afgeleide prijscomponent draagt zijn eigen zero_allowed/negative_allowed op import_field_mapping
-- (004-2). De basisprijs heeft geen mappingrij en kan er ook geen krijgen: R-STR-06 verbiedt een tweede
-- bron naast record_base_price_field. Daarom staan deze twee schakelaars op de revisie zelf.
--
-- Default false: een basisprijs 0 of negatief is een betekenisvolle, verdachte waarde en wordt
-- geweigerd tenzij de beheerder ze uitdrukkelijk toelaat. Dat wijzigt het fase 2-gedrag, waarin een
-- basisprijs 0 nog gestaged werd.
alter table import_definition_revision add column base_price_zero_allowed boolean not null default false;
alter table import_definition_revision add column base_price_negative_allowed boolean not null default false;

--rollback alter table import_definition_revision drop column base_price_negative_allowed;
--rollback alter table import_definition_revision drop column base_price_zero_allowed;

-- =============================================================================================
-- Bouwstap 3e: prijshistoriek en afwijkingscontrole (ontwerp fase 3 par. 2 sub-changesets 004-7
-- en het 3e-deel van 004-11, par. 0 afwijking B, R-PRI-10..R-PRI-13). Alles hierboven is reeds
-- uitgevoerd en blijft ongewijzigd.
--
-- FINANCIEEL: ook hier zijn bedragen numeric(24,6) en percentages numeric(24,12). De historiek is
-- append-only: een eenmaal vastgelegde goedgekeurde dagwaarde wordt nooit overschreven of
-- gecorrigeerd, want de afwijkingscontrole van morgen rekent erop.
-- =============================================================================================

--changeset catalogimport:004-7-catalog-price-observation
--comment Goedgekeurde prijswaarden per kalenderdag als referentie voor de afwijkingscontrole (ontwerp fase 3 par. 2 004-7, R-PRI-10/R-PRI-13).

-- Waarom een aparte tabel naast catalog_source_state_price: die laatste draagt uitsluitend de
-- LAATSTE aanvaarde waarde. De afwijkingscontrole vergelijkt daarnaast met het gemiddelde van de
-- laatste 50 en 200 goedgekeurde dagwaarden (R-PRI-10); zonder historiek bestaat dat gemiddelde niet
-- en zou de controle stil terugvallen op één enkele vorige waarde.
--
-- De unieke sleutel (koppeling, identiteit, component, dag) dwingt R-PRI-13 op databaseniveau af:
-- hoogstens één goedgekeurde waarde per kalenderdag per identiteit + component. Samen met
-- "insert ... where not exists" blijft bij twee aanvaardingen op dezelfde dag de EERSTE waarde staan
-- (aanname A16) - de historiek wordt nooit achteraf herschreven.
--
-- Enkel goedgekeurde waarden komen hier terecht (in fase 3: accept-baseline, later de publicatie).
-- Een kandidaatprijs uit een lopende screening staat NOOIT in deze tabel: anders zou een nog niet
-- beoordeelde afwijking zichzelf tot referentie promoveren.
create table catalog_price_observation (
    id              bigint generated by default as identity,
    import_link_id  bigint not null,
    identity_hash   ${hash.type} not null,
    component_code  varchar(20) not null,
    observation_date date not null,
    amount          numeric(24,6),
    percentage      numeric(24,12),
    currency        varchar(3),
    source_state_id bigint,
    batch_id        bigint,
    accepted_by     varchar(100),
    created_at      timestamp with time zone not null,
    constraint pk_catalog_price_observation primary key (id),
    constraint uk_catalog_price_observation_day unique (import_link_id, identity_hash, component_code, observation_date),
    constraint fk_catalog_price_observation_link foreign key (import_link_id) references import_link (id),
    constraint fk_catalog_price_observation_state foreign key (source_state_id) references catalog_source_state (id),
    constraint fk_catalog_price_observation_batch foreign key (batch_id) references import_batch (id)
);

-- De leesrichting van de afwijkingscontrole: de laatste N dagwaarden van één identiteit + component.
-- Aflopend op datum, zodat het venster van 50 respectievelijk 200 waarden vooraan gevonden wordt.
create index idx_catalog_price_observation_window
    on catalog_price_observation (import_link_id, identity_hash, component_code, observation_date desc);

--rollback drop table catalog_price_observation;

--changeset catalogimport:004-11c-import-batch-price-progress
--comment Hervatpunt van de prijscontrolepass E3 (ontwerp fase 3 par. 2 004-11, par. 3.1).

-- Eigen voortgangskolom, net als mutation_progress_row_number: de prijscontrole is een afzonderlijk
-- hervatbare pass. Na een onderbroken verwerking wordt enkel het deel na dit regelnummer opnieuw
-- beoordeeld, zodat er geen dubbele prijsissues ontstaan.
--
-- not null default 0 (en niet nullable): 0 betekent hier "nog niets verwerkt", een volwaardige
-- beginwaarde en geen onbekende. De overige 004-11-kolommen (tellers, classify/reference-voortgang,
-- baseline_approved_by) volgen in 3f-3h onder hun eigen id.
alter table import_batch add column price_progress_row_number bigint not null default 0;

--rollback alter table import_batch drop column price_progress_row_number;

--changeset catalogimport:004-13b-import-mutation-domain-mask-width
--comment domain_mask verbreden van varchar(100) naar varchar(200) (risico uit bouwstap 3d).

-- Met de zeven geseede prijscomponenten is het langst mogelijke domeinmasker 94 tekens
-- (ARTICLE,PRICE,PRICE:BASE_PRICE,PRICE:AKP,...). Eén extra component of een langere componentcode
-- zou er niet meer in passen; MutationDao.verifyMaskFits weigert dat vooraf, want een afgekapt masker
-- zou verbergen WELKE prijscomponent gewijzigd is.
--
-- Verbreden is additief: bestaande waarden blijven byte voor byte staan en elke bestaande query blijft
-- werken. De standaardvorm "alter column ... set data type" wordt zowel door PostgreSQL als door H2
-- begrepen, zodat hier geen dbms-specifieke variant nodig is. De terugdraaiactie verkleint de kolom
-- weer en faalt bewust wanneer er dan al een langere waarde in staat: een masker wordt nooit afgekapt.
alter table import_mutation alter column domain_mask set data type varchar(200);

--rollback alter table import_mutation alter column domain_mask set data type varchar(100);

-- =============================================================================================
-- Bouwstap 3f: kritieke koppelreferenties (ontwerp fase 3 par. 2 sub-changesets 004-8, 004-9,
-- 004-13 en het 3f-deel van 004-11; R-ID-03/R-ID-04, R-REF-01..R-REF-09). Alles hierboven is
-- reeds uitgevoerd en blijft ongewijzigd.
--
-- IDENTITEIT: EAN, PIM-ID, CAB-ID en E_MARK+ARTICLE_REFERENCE zijn geen gewone importvelden maar
-- kritieke koppelreferenties naar een intern artikel (businessanalyse par. 14.23.3). Een andere,
-- verwijderde, hergebruikte of dubbelzinnige waarde wordt NOOIT een gewone update: zij wordt een
-- afzonderlijk identiteitsincident dat een mens moet goedkeuren.
-- =============================================================================================

--changeset catalogimport:004-8-catalog-reference-state
--comment Actieve en historische kritieke koppelreferenties per bibliotheek (ontwerp fase 3 par. 2 004-8, R-REF-01/R-REF-04/R-REF-06).

-- value_normalised is de vergelijkingswaarde, value_raw de waarde zoals de leverancier ze stuurde.
-- Beide worden bewaard (R-REF-01): '000123', '123' en 'AB-123' blijven verschillende referenties,
-- want de normalisatie verwijdert geen voorloopnullen en doet geen hoofdletterconversie
-- (businessanalyse par. 14.23.7, "Normatieve normalisatie van CAB-/PIM-ID").
--
-- active_marker draagt TRUE zolang de rij de actieve koppeling is en NULL zodra ze historiek wordt.
-- NULL-waarden botsen niet in een unieke constraint (zelfde truc als import_batch.open_marker), dus
-- dwingt uk_catalog_reference_state_active op databaseniveau af dat eenzelfde referentiewaarde binnen
-- een bibliotheek hoogstens bij EEN aanbieding actief is - ook onder gelijktijdige acceptaties van
-- twee batches. De historiek van dezelfde waarde mag wel meermaals bestaan.
--
-- De unieke index begint met (library_code, reference_type, value_normalised): dat is precies de
-- join van de referentiecontrole, dus er is geen tweede index op dezelfde kolommen nodig.
create table catalog_reference_state (
    id               bigint generated by default as identity,
    library_code     varchar(20) not null,
    reference_type   varchar(30) not null,
    value_normalised varchar(200) not null,
    value_raw        varchar(200) not null,
    source_state_id  bigint not null,
    import_link_id   bigint not null,
    active_marker    boolean,
    accepted_by      varchar(100),
    accepted_at      timestamp with time zone,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    constraint pk_catalog_reference_state primary key (id),
    constraint uk_catalog_reference_state_active
        unique (library_code, reference_type, value_normalised, active_marker),
    constraint fk_catalog_reference_state_source_state foreign key (source_state_id)
        references catalog_source_state (id),
    constraint fk_catalog_reference_state_link foreign key (import_link_id) references import_link (id),
    -- FALSE zou een derde toestand invoeren die de NULL-markertruc stilzwijgend uitschakelt.
    constraint ck_catalog_reference_state_active_marker
        check (active_marker is null or active_marker = true)
);

create index idx_catalog_reference_state_state on catalog_reference_state (source_state_id, reference_type);

--rollback drop table catalog_reference_state;

--changeset catalogimport:004-9-import-candidate-reference
--comment Genormaliseerde kritieke referenties van een gestagede kandidaat (ontwerp fase 3 par. 2 004-9, R-REF-01/R-REF-03).

-- JDBC-only, net als import_candidate_stage en import_candidate_price: een levering kan een miljoen
-- regels met meerdere referenties bevatten. De sleutel is (batch_id, row_number, reference_type) -
-- geen gegenereerde id - zodat een hervatte microbatch nooit een tweede rij voor dezelfde referentie
-- kan schrijven.
--
-- Er bestaat een rij per GEMAPTE referentie, ook wanneer de bron ze leeg levert (is_empty = true).
-- Dat onderscheid is de kern van R-REF-03: "gemapt maar leeg" is een uitspraak van de leverancier
-- (de referentie verdwijnt) en "niet gemapt" is geen uitspraak (er is geen rij, dus geen oordeel).
-- Een lege referentie draagt daarom geen vergelijkingswaarde; de check laat die twee niet door elkaar
-- lopen.
--
-- on delete cascade: de staging is een geheel. Bij een technisch mislukte poging wordt de staging
-- opgeruimd en mogen haar referenties niet als wees achterblijven.
create table import_candidate_reference (
    batch_id                bigint not null,
    row_number              bigint not null,
    reference_type          varchar(30) not null,
    value_raw               varchar(200),
    value_normalised        varchar(200),
    is_empty                boolean not null,
    match_result            varchar(30),
    matched_source_state_id bigint,
    constraint pk_import_candidate_reference primary key (batch_id, row_number, reference_type),
    constraint fk_import_candidate_reference_stage foreign key (batch_id, row_number)
        references import_candidate_stage (batch_id, row_number) on delete cascade,
    constraint ck_import_candidate_reference_empty
        check ((is_empty = true and value_normalised is null)
            or (is_empty = false and value_normalised is not null)),
    constraint ck_import_candidate_reference_match
        check (match_result is null
            or match_result in ('NEW', 'SAME', 'CHANGED', 'REUSED', 'AMBIGUOUS', 'REMOVED'))
);

-- De join van de referentiecontrole en van de duplicaatcontrole binnen de levering.
create index idx_import_candidate_reference_value
    on import_candidate_reference (batch_id, reference_type, value_normalised);

--rollback drop table import_candidate_reference;

--changeset catalogimport:004-11d-import-batch-reference-progress
--comment Incidentteller en de hervatpunten van de passes E1 en E2 (ontwerp fase 3 par. 2 004-11, par. 3.1).

-- identity_incident_count is nullable: NULL betekent onbekend (de delta is nooit bereikt), nooit stil 0.
-- Samen met de bestaande tellers geldt vanaf bouwstap 3f:
--   valid = new + changed + unchanged + duplicate_identity_count + identity_incident_count
-- Een vastgehouden record is namelijk wel degelijk geldig gelezen; het wordt enkel niet doorgelaten.
--
-- classify_progress_row_number en reference_progress_row_number zijn not null default 0, net als
-- mutation_progress_row_number en price_progress_row_number: 0 is een volwaardige beginwaarde
-- ("nog niets verwerkt"), geen onbekende. Elke pass heeft een eigen hervatpunt, zodat een
-- onderbroken verwerking geen enkele chunk een tweede keer beoordeelt.
alter table import_batch add column identity_incident_count bigint;
alter table import_batch add column classify_progress_row_number bigint not null default 0;
alter table import_batch add column reference_progress_row_number bigint not null default 0;

--rollback alter table import_batch drop column reference_progress_row_number;
--rollback alter table import_batch drop column classify_progress_row_number;
--rollback alter table import_batch drop column identity_incident_count;

--changeset catalogimport:004-13-import-mutation-reference-incident
--comment De mutatielijst draagt het kritieke referentie-incident (ontwerp fase 3 par. 2 004-13, R-REF-02..R-REF-05, R-REF-09).

-- action_type wordt verbreed van varchar(20) naar varchar(40): 'IDENTITY_REFERENCE_INCIDENT' telt 27
-- tekens. Verbreden is additief - bestaande waarden blijven byte voor byte staan - en de standaardvorm
-- "alter column ... set data type" wordt door PostgreSQL en H2 begrepen. Zonder deze verbreding zou de
-- insert van een incident halverwege een levering op een databasefout stranden.
alter table import_mutation alter column action_type set data type varchar(40);

-- Voor- en nawaarde van de referentie staan als leesbare tekst op de mutatie (par. 15.12): een
-- beslisser moet oude waarde, nieuwe waarde en referentietype zien zonder de staging te moeten
-- raadplegen - die wordt na publicatie opgeruimd. issue_group_id koppelt het incident later aan zijn
-- bulkincident (bouwstap 3g); in 3f blijft de kolom leeg.
alter table import_mutation add column reference_type varchar(30);
alter table import_mutation add column before_reference_value varchar(200);
alter table import_mutation add column after_reference_value varchar(200);
alter table import_mutation add column issue_group_id bigint;

alter table import_mutation add constraint fk_import_mutation_issue_group
    foreign key (issue_group_id) references import_issue_group (id);

-- De marker-check wordt gedropt en heruitgegeven: ze somt de toegelaten action_type-waarden op en
-- moet dus het nieuwe soort kennen. Heruitgeven (niet uitbreiden) omdat een check-constraint nergens
-- portabel te wijzigen is. De eisen per soort blijven zo streng als ze waren en worden voor het nieuwe
-- soort even expliciet:
--   IMPORT_MARKER                -> geen identiteit, geen referentie;
--   CREATE/UPDATE                -> volledige aanbiedingsidentiteit, geen referentievelden;
--   IDENTITY_REFERENCE_INCIDENT  -> volledige identiteit MET identity_hash, een referentietype en
--                                   minstens een van beide referentiewaarden. Een incident zonder
--                                   oude en zonder nieuwe waarde zou niets vaststellen.
alter table import_mutation drop constraint ck_import_mutation_marker;

alter table import_mutation add constraint ck_import_mutation_marker check (
    (action_type = 'IMPORT_MARKER'
        and target_domain = 'IMPORT'
        and status = 'RECORDED'
        and identity_supplier is null
        and identity_supplier_group is null
        and identity_supplier_reference is null
        and identity_hash is null
        and reference_type is null)
    or (action_type in ('CREATE', 'UPDATE')
        and target_domain <> 'IMPORT'
        and identity_supplier is not null
        and identity_supplier_group is not null
        and identity_supplier_reference is not null
        and reference_type is null)
    or (action_type = 'IDENTITY_REFERENCE_INCIDENT'
        and target_domain <> 'IMPORT'
        and identity_supplier is not null
        and identity_supplier_group is not null
        and identity_supplier_reference is not null
        and identity_hash is not null
        and reference_type is not null
        and (before_reference_value is not null or after_reference_value is not null))
);

--rollback alter table import_mutation drop constraint ck_import_mutation_marker;
--rollback alter table import_mutation add constraint ck_import_mutation_marker check ((action_type = 'IMPORT_MARKER' and target_domain = 'IMPORT' and status = 'RECORDED' and identity_supplier is null and identity_supplier_group is null and identity_supplier_reference is null and identity_hash is null) or (action_type in ('CREATE', 'UPDATE') and target_domain <> 'IMPORT' and identity_supplier is not null and identity_supplier_group is not null and identity_supplier_reference is not null));
--rollback alter table import_mutation drop constraint fk_import_mutation_issue_group;
--rollback alter table import_mutation drop column issue_group_id;
--rollback alter table import_mutation drop column after_reference_value;
--rollback alter table import_mutation drop column before_reference_value;
--rollback alter table import_mutation drop column reference_type;
--rollback alter table import_mutation alter column action_type set data type varchar(20);

-- =============================================================================================
-- Bouwstap 3g: groepering van gelijksoortige problemen en bulkincidenten (ontwerp fase 3 par. 2
-- sub-changeset 004-4 - de tabel bestaat al sinds 3a en wordt nu gevuld -, par. 3.1 pass E4,
-- R-THR-04, R-ISS-03, R-PRI-14, R-REF-07). De reeds uitgevoerde changesets hierboven blijven
-- ongewijzigd; enkel additieve kolommen komen erbij.
-- =============================================================================================

--changeset catalogimport:004-12b-import-row-issue-signature
--comment De foutsignatuur van een issuerij, zodat pass E4 set-based kan groeperen (ontwerp fase 3 par. 3.2, R-THR-04).

-- Waarom deze kolom bestaat: de groepering moet set-based gebeuren (miljoenen rijen, geen
-- groepering in het geheugen). Voor een gewone foutgroep zou (issue_code, field_name) volstaan,
-- maar voor een prijs- of identiteitsincident bestaat de signatuur uit gegevens die NIET op de
-- issuerij staan (prijscomponent + richting, referentietype + soort incident). Die in SQL
-- herberekenen zou de financiële en de identiteitsregel een tweede keer implementeren. De
-- signatuur wordt daarom vastgelegd op het moment van vaststellen, net als ernst en domein
-- (R-ISS-02), en pass E4 doet nog uitsluitend een join.
--
-- Nullable: een probleem dat per definitie hoogstens één keer voorkomt (een blokkade van de
-- volledige levering) hoort bij geen enkele groep. NULL is daar "hoort nergens bij", nooit "nog
-- niet bepaald".
alter table import_row_issue add column signature varchar(300);

create index idx_import_row_issue_signature on import_row_issue (batch_id, issue_code, signature);

--rollback drop index idx_import_row_issue_signature;
--rollback alter table import_row_issue drop column signature;

--changeset catalogimport:004-11e-import-batch-bulk-incident-count
--comment Aantal vastgestelde bulkincidenten van deze batch (ontwerp fase 3 par. 2 004-11, R-THR-04).

-- Nullable zoals elke andere teller: NULL betekent "niet vastgesteld" (lopende of technisch
-- mislukte batch), nooit stil 0. De overige 004-11-tellers (critical_issue_count, warning_count,
-- awaiting_approval_count) horen bij bouwstap 3h en komen daar onder hun eigen id.
alter table import_batch add column bulk_incident_count bigint;

--rollback alter table import_batch drop column bulk_incident_count;

--changeset catalogimport:004-10c-import-definition-revision-bulk-share
--comment Bulkincident als percentage van de gecontroleerde scope, per revisie (beslissingslog 20/09, ontwerp par. 15.2).

-- Beslissing van de mens (20/09): elke drempel is ALTIJD een percentage van de omvang en nooit een
-- vast aantal. Een vaste grens van honderd records maakt een koppeling met tweehonderd artikelen
-- onbruikbaar en een koppeling met een miljoen artikelen overgevoelig. Wie een kleine leverancier
-- anders wil behandelen, zet dit percentage hoger: een zichtbare, geauditeerde keuze per revisie in
-- plaats van een verborgen constante in de code.
--
-- De bestaande absolute kolommen (creation_threshold_absolute, max_critical_records,
-- max_rejected_records) worden NIET hernoemd en NIET verwijderd: dat zou een contractbreuk zijn op
-- een reeds uitgevoerde changeset. Ze blijven staan en worden niet meer gebruikt.
--
-- not null met default 1: zonder percentage zou er geen bulkregel bestaan, en een NULL-drempel die
-- stilzwijgend "nooit bulk" betekent, is precies het soort onzichtbare uitschakeling dat vermeden
-- moet worden.
alter table import_definition_revision add column bulk_incident_share_percent numeric(24,12) not null default 1;

--rollback alter table import_definition_revision drop column bulk_incident_share_percent;
