--liquibase formatted sql

-- Fase 3 (docs/design/fase3-rules-design.md par. 2): additief naast 001, 002 en 003, die ongewijzigd blijven.
-- Bouwstap 3a levert enkel de sub-changesets die het issuemodel nodig heeft: 004-4, 004-11 (basisdeel) en
-- 004-12. De overige sub-changesets uit par. 2 (004-1..3, 004-5..10, 004-13, 004-14) worden door de
-- volgende bouwstappen additief aan dit bestand toegevoegd, met hun eigen id.
--
-- Een reeds uitgevoerde changeset wordt nooit bijgewerkt (checksum): de resterende kolommen van 004-11
-- (tellers en voortgangskolommen van de passes E1-E4) krijgen daarom in bouwstap 3b-3h een eigen id
-- 004-11b, niet een uitbreiding van 004-11 hieronder.

--changeset catalogimport:004-4-import-issue-group
--comment Samenvatting per foutsignatuur binnen een batch (ontwerp fase 3 par. 2, R-ISS-03/R-THR-04). De tabel wordt in bouwstap 3a enkel aangemaakt; vullen en bulkincidenten zijn bouwstap 3g.

-- occurrence_count is het VOLLEDIGE aantal voorvallen, recorded_sample_count het aantal bewaarde
-- voorbeeldrijen in import_row_issue. Die twee lopen bewust uiteen: bij een miljoen identieke fouten
-- worden er hoogstens N voorbeelden bewaard, maar het totaal mag nooit verloren gaan.
create table import_issue_group (
    id                   bigint generated by default as identity,
    batch_id             bigint not null,
    issue_code           varchar(60) not null,
    signature            varchar(300) not null,
    severity             varchar(20) not null,
    issue_domain         varchar(40) not null,
    control_level        varchar(20) not null,
    impact_scope         varchar(20) not null,
    incident_kind        varchar(30) not null default 'GENERIC',
    occurrence_count     bigint not null,
    recorded_sample_count integer not null,
    scope_record_count   bigint,
    share_percent        numeric(24,12),
    is_bulk_incident     boolean not null default false,
    price_component_code varchar(20),
    deviation_direction  varchar(10),
    dominant_factor      numeric(24,12),
    reference_type       varchar(30),
    pattern_description  varchar(500),
    first_row_number     bigint,
    first_detected_at    timestamp with time zone,
    last_detected_at     timestamp with time zone,
    handling_status      varchar(30) not null default 'DETECTED',
    constraint pk_import_issue_group primary key (id),
    constraint uk_import_issue_group_signature unique (batch_id, issue_code, signature),
    constraint fk_import_issue_group_batch foreign key (batch_id) references import_batch (id),
    constraint ck_import_issue_group_incident_kind
        check (incident_kind in ('GENERIC', 'PRICE', 'IDENTITY', 'CREATION'))
);

create index idx_import_issue_group_batch_severity on import_issue_group (batch_id, severity);

--rollback drop table import_issue_group;

--changeset catalogimport:004-11-import-batch-validation-result
--comment Inhoudelijk eindoordeel als aparte statusas naast status (ontwerp fase 3 par. 0 afwijking D, R-THR-06).

-- Nullable: NULL betekent "nog niet vastgesteld" (lopende batch) of "niets vast te stellen"
-- (technische fout, FAILED). Nooit stil VALID. De overige 004-11-kolommen (tellers, voortgang per
-- pass) volgen in een latere bouwstap onder id 004-11b.
alter table import_batch add column validation_result varchar(30);

--rollback alter table import_batch drop column validation_result;

--changeset catalogimport:004-12-import-row-issue-control-model
--comment import_row_issue draagt voortaan alle drie de controleniveaus (ontwerp fase 3 par. 2 004-12, par. 3.3).

-- De tabel wordt UITGEBREID, niet vervangen of hernoemd (aanname A14): geen datamigratie, en de
-- fase 2-contracten blijven werken. De defaults zijn zo gekozen dat elke bestaande rij - allemaal
-- regelproblemen uit fase 2 - geldig blijft zonder update-statement.
--
-- row_number en delivery_file_id worden nullable: een probleem op leverings- of structuurniveau
-- (leeg bestand, ontbrekende headerkolom, configuratiefout) hoort bij geen enkele bronregel. Een
-- verzonnen regelnummer 0 zou dat verschil verbergen.
alter table import_row_issue alter column row_number drop not null;
alter table import_row_issue alter column delivery_file_id drop not null;

alter table import_row_issue add column issue_domain varchar(40) not null default 'MAPPING_VALIDATION';
alter table import_row_issue add column control_level varchar(20) not null default 'RECORD';
alter table import_row_issue add column impact_scope varchar(20) not null default 'RECORD';
alter table import_row_issue add column issue_group_id bigint;
alter table import_row_issue add column handling_status varchar(30) not null default 'DETECTED';
alter table import_row_issue add column rule_config_version integer;
alter table import_row_issue add column expected_value varchar(200);
alter table import_row_issue add column occurrence_seq integer;

alter table import_row_issue add constraint fk_import_row_issue_group
    foreign key (issue_group_id) references import_issue_group (id);

create index idx_import_row_issue_batch_severity on import_row_issue (batch_id, severity);
create index idx_import_row_issue_group on import_row_issue (issue_group_id);

--rollback drop index idx_import_row_issue_group;
--rollback drop index idx_import_row_issue_batch_severity;
--rollback alter table import_row_issue drop constraint fk_import_row_issue_group;
--rollback alter table import_row_issue drop column occurrence_seq;
--rollback alter table import_row_issue drop column expected_value;
--rollback alter table import_row_issue drop column rule_config_version;
--rollback alter table import_row_issue drop column handling_status;
--rollback alter table import_row_issue drop column issue_group_id;
--rollback alter table import_row_issue drop column impact_scope;
--rollback alter table import_row_issue drop column control_level;
--rollback alter table import_row_issue drop column issue_domain;
--rollback alter table import_row_issue alter column delivery_file_id set not null;
--rollback alter table import_row_issue alter column row_number set not null;
