--liquibase formatted sql

-- Fase 4 (docs/design/fase4-publication-bundle-design.md par. 2, docs/decisions.md "Fase 4: ontwerp
-- Publicatiebundel"): additief naast 001-004, die ongewijzigd blijven. Bouwstap 4a levert enkel het
-- schema (005-1 t/m 005-4); service-/REST-logica volgt in 4b-4f.
--
-- Ontwerpkeuze (bewust, zie design par. 2): het lidmaatschap van een batch in een bundel zit op
-- BATCHNIVEAU (publication_bundle_batch), niet op mutatieniveau. Er komt daarom GEEN
-- publication_bundle_id-kolom op import_mutation: de bundel van een mutatie is af te leiden via
-- batch_id -> publication_bundle_batch (active) -> bundle_id.

--changeset catalogimport:005-1-publication-bundle
--comment De Publicatiebundel: eenheid van goedkeuring/bevriezing/publicatie over meerdere batches heen (design par. 2, R-BND).

-- target_mode heeft BEWUST GEEN default: een bundel moet altijd expliciet SIMULATION, TRIAL_LIBRARY
-- of PRODUCTION kiezen. Een stille default zou ofwel per ongeluk naar productie publiceren, ofwel een
-- echte productiebundel laten lijken op een proef.
--
-- De tien tellers zijn nullable bigint, net als de tellers op import_batch (par. 3a): NULL betekent
-- "niet vastgesteld" (nog niet bevroren), nooit stil 0. Ze worden pas bij bevriezen (bouwstap 4e)
-- berekend en bewaard.
--
-- content_hash gebruikt ${hash.type} (bytea/varbinary(32), zie db.changelog-master.yaml) en is enkel
-- gevuld zodra de bundel FROZEN is; de check hieronder dwingt dat af.
create table publication_bundle (
    id                       bigint generated by default as identity,
    bundle_reference         varchar(100) not null,
    description              varchar(500),
    status                   varchar(30) not null,
    target_mode              varchar(30) not null,
    target_moment            timestamp with time zone,
    publication_policy       varchar(1000),
    created_by               varchar(100) not null,
    created_at               timestamp with time zone not null,
    frozen_by                varchar(100),
    frozen_at                timestamp with time zone,
    frozen_reason            varchar(500),
    cancelled_by             varchar(100),
    cancelled_at             timestamp with time zone,
    cancelled_reason         varchar(500),
    content_hash             ${hash.type},
    idempotency_key          varchar(200) not null,
    batch_count              bigint,
    content_mutation_count   bigint,
    ready_count              bigint,
    rejected_count           bigint,
    blocked_count            bigint,
    expired_count            bigint,
    identity_incident_count  bigint,
    bulk_incident_count      bigint,
    critical_issue_count     bigint,
    warning_count            bigint,
    constraint pk_publication_bundle primary key (id),
    constraint uk_publication_bundle_reference unique (bundle_reference),
    constraint uk_publication_bundle_idempotency unique (idempotency_key),
    constraint ck_publication_bundle_status check (status in
        ('ASSEMBLING', 'FROZEN', 'CANCELLED', 'PUBLISHING', 'PARTIALLY_PUBLISHED', 'PUBLISHED',
         'PUBLICATION_FAILED')),
    constraint ck_publication_bundle_target_mode check (target_mode in
        ('SIMULATION', 'TRIAL_LIBRARY', 'PRODUCTION')),
    -- R-FRZ: bevriezen berekent en bewaart in één transactie frozen_by, frozen_at en content_hash;
    -- geen van de drie mag zonder de andere twee bestaan zodra de status FROZEN is.
    constraint ck_publication_bundle_frozen check (status <> 'FROZEN'
        or (frozen_by is not null and frozen_at is not null and content_hash is not null)),
    -- Annuleren vereist altijd een reden (R-FRZ), net als frozen_reason bij bevriezen.
    constraint ck_publication_bundle_cancelled check (status <> 'CANCELLED'
        or (cancelled_by is not null and cancelled_at is not null and cancelled_reason is not null))
);

--rollback drop table publication_bundle;

--changeset catalogimport:005-2-publication-bundle-batch
--comment Lidmaatschap van een batch in een bundel, op BATCHNIVEAU (design par. 2, R-BND). Een batch heeft hoogstens één actief lidmaatschap, over alle bundels heen.

-- import_link_id staat gedenormaliseerd op de koppelrij (design par. 2): de conflictquery bij
-- bevriezen (design par. 3) joint op import_link_id + identity_hash zonder telkens via import_batch te
-- moeten gaan.
--
-- active_marker is TRUE zolang het lidmaatschap actief is en NULL zodra het verwijderd is - zelfde
-- NULL-markertruc als import_batch.open_marker (002) en catalog_reference_state.active_marker (004-8).
-- uk_publication_bundle_batch_active is de kernconstraint van dit ontwerp: ze garandeert op
-- databaseniveau, ook onder gelijktijdige toevoegingen, dat een batch nooit in twee bundels tegelijk
-- actief lid is.
create table publication_bundle_batch (
    id             bigint generated by default as identity,
    bundle_id      bigint not null,
    batch_id       bigint not null,
    import_link_id bigint not null,
    added_by       varchar(100) not null,
    added_at       timestamp with time zone not null,
    removed_by     varchar(100),
    removed_at     timestamp with time zone,
    removed_reason varchar(500),
    active_marker  boolean,
    constraint pk_publication_bundle_batch primary key (id),
    constraint fk_publication_bundle_batch_bundle foreign key (bundle_id)
        references publication_bundle (id),
    constraint fk_publication_bundle_batch_batch foreign key (batch_id)
        references import_batch (id),
    constraint fk_publication_bundle_batch_link foreign key (import_link_id)
        references import_link (id),
    constraint uk_publication_bundle_batch_bundle unique (bundle_id, batch_id),
    constraint uk_publication_bundle_batch_active unique (batch_id, active_marker),
    -- FALSE zou een derde toestand invoeren die de NULL-markertruc stilzwijgend uitschakelt (zelfde
    -- redenering als ck_catalog_reference_state_active_marker in 004-8).
    constraint ck_publication_bundle_batch_marker check (active_marker is null or active_marker = true),
    -- Actief lidmaatschap: geen van de drie removed-velden gevuld, active_marker TRUE. Verwijderd
    -- lidmaatschap: alle drie gevuld, active_marker NULL. Geen tussenvorm mogelijk.
    constraint ck_publication_bundle_batch_removed check (
        (removed_by is null and removed_at is null and removed_reason is null and active_marker = true)
        or (removed_by is not null and removed_at is not null and removed_reason is not null
            and active_marker is null)
    )
);

create index idx_publication_bundle_batch_bundle on publication_bundle_batch (bundle_id);
create index idx_publication_bundle_batch_link on publication_bundle_batch (import_link_id, active_marker);

--rollback drop index idx_publication_bundle_batch_link;
--rollback drop index idx_publication_bundle_batch_bundle;
--rollback drop table publication_bundle_batch;

--changeset catalogimport:005-3-publication-decision
--comment Append-only beslissingsregister per mutatie/groep/bundel (design par. 2, R-DEC; retentie 7 jaar).

-- Eén rij per genomen beslissing, nooit bijgewerkt of verwijderd: een herziening (R-DEC) schrijft een
-- NIEUWE rij, de oude blijft staan. mutation_id is enkel gevuld bij scope MUTATION; bij GROUP/BUNDLE
-- staat de canoniek gerenderde filter/reden in selection_filter/reason en telt affected_count het
-- werkelijke aantal geraakte mutaties.
create table publication_decision (
    id               bigint generated by default as identity,
    bundle_id        bigint not null,
    mutation_id      bigint,
    decision_kind    varchar(30) not null,
    decision_scope   varchar(20) not null,
    selection_filter varchar(500),
    previous_status  varchar(40),
    new_status       varchar(40),
    affected_count   bigint not null default 1,
    decided_by       varchar(100) not null,
    decided_at       timestamp with time zone not null,
    reason           varchar(500) not null,
    constraint pk_publication_decision primary key (id),
    constraint fk_publication_decision_bundle foreign key (bundle_id)
        references publication_bundle (id),
    constraint fk_publication_decision_mutation foreign key (mutation_id)
        references import_mutation (id),
    constraint ck_publication_decision_kind check (decision_kind in
        ('APPROVE', 'REJECT', 'AUTO_APPROVE_PLANNED', 'FREEZE', 'CANCEL')),
    constraint ck_publication_decision_scope check (decision_scope in ('MUTATION', 'GROUP', 'BUNDLE')),
    -- MUTATION-scope beslist over exact één mutatie: mutation_id gevuld en affected_count = 1. Een
    -- GROUP- of BUNDLE-beslissing draagt nooit een individuele mutatieverwijzing.
    constraint ck_publication_decision_mutation check (
        (decision_scope = 'MUTATION' and mutation_id is not null and affected_count = 1)
        or (decision_scope <> 'MUTATION' and mutation_id is null)
    )
);

create index idx_publication_decision_bundle_decided on publication_decision (bundle_id, decided_at);
create index idx_publication_decision_mutation on publication_decision (mutation_id);

--rollback drop index idx_publication_decision_mutation;
--rollback drop index idx_publication_decision_bundle_decided;
--rollback drop table publication_decision;

--changeset catalogimport:005-4-import-mutation-decision
--comment Vier additieve beslisvelden op de mutatielijst (design par. 2, R-DEC). Elke mutatie draagt haar eigen decided_by/decided_at/decided_from_status/decision_id, ook bij een groepsactie.

-- Alle vier nullable en samen leeg of samen gevuld (check hieronder): een mutatie die nog niet
-- beslist is, draagt geen van de vier. decided_from_status bewaart de status vlak voor de beslissing
-- (PLANNED of AWAITING_APPROVAL, of de tegenovergestelde eindstatus bij een herziening), zodat de
-- audit-trail leesbaar blijft zonder de append-only publication_decision te moeten joinen.
--
-- Geen decision_reason op de mutatie zelf: de reden staat één keer op publication_decision, niet
-- gedupliceerd over mogelijk honderdduizenden mutatierijen (design par. 2).
alter table import_mutation add column decided_by varchar(100);
alter table import_mutation add column decided_at timestamp with time zone;
alter table import_mutation add column decided_from_status varchar(40);
alter table import_mutation add column decision_id bigint;

alter table import_mutation add constraint fk_import_mutation_decision
    foreign key (decision_id) references publication_decision (id);

alter table import_mutation add constraint ck_import_mutation_decision_fields check (
    (decided_by is null and decided_at is null and decided_from_status is null and decision_id is null)
    or (decided_by is not null and decided_at is not null and decided_from_status is not null
        and decision_id is not null)
);

-- Een afgekeurde mutatie moet altijd naar haar beslissing (en dus haar verplichte reden) kunnen wijzen.
alter table import_mutation add constraint ck_import_mutation_rejected_decided
    check (status <> 'REJECTED' or decision_id is not null);

-- Draagt de conflictquery bij bevriezen (design par. 3): twee publiceerbare mutaties op dezelfde
-- (import_link_id, identity_hash) uit verschillende batches.
create index idx_import_mutation_link_identity_status
    on import_mutation (import_link_id, identity_hash, status);

--rollback drop index idx_import_mutation_link_identity_status;
--rollback alter table import_mutation drop constraint ck_import_mutation_rejected_decided;
--rollback alter table import_mutation drop constraint ck_import_mutation_decision_fields;
--rollback alter table import_mutation drop constraint fk_import_mutation_decision;
--rollback alter table import_mutation drop column decision_id;
--rollback alter table import_mutation drop column decided_from_status;
--rollback alter table import_mutation drop column decided_at;
--rollback alter table import_mutation drop column decided_by;
