--liquibase formatted sql

-- Sjabloon + bookmarks (docs/decisions.md 2026-09-23 "Fase 1-achtig: domeinmodel sjabloon +
-- bookmarks", businessanalyse par. 14.14-14.20). Volledig ADDITIEF naast 001-005, die ongewijzigd
-- blijven: geen enkele bestaande kolom wordt hernoemd, verwijderd of van type gewijzigd.
--
-- Kernkeuze van het ontwerp: een sjabloon is GEEN nieuwe entiteit maar een bestaande
-- import_definition met usage_type = 'REUSABLE_TEMPLATE', met hergebruik van
-- import_definition_revision als versiebegrip. Daarom komen er hier enkel vier nieuwe tabellen bij
-- plus een databaseguard; er is geen parallel definitie- of versiemodel.
--
-- Deze changeset levert enkel het SCHEMA (Fase 1: entiteiten + migratie). Service-, REST- en
-- UI-laag (materialisatiewizard, sjabloonversievergelijking, bulkcreatie, de lock op LINK-waarden
-- bij een open batch) volgen in een latere bouwstap.

--changeset catalogimport:006-1-import-definition-bookmark
--comment Declaratie van een bookmark op REVISIENIVEAU van een sjabloon (decisions.md 2026-09-23, keuze 1).

-- De declaratie hangt aan de REVISIE, niet aan de definitie: een sjabloon dat een bookmark
-- toevoegt of laat vallen is een nieuwe sjabloonversie, precies zoals elke andere structuurwijziging
-- (par. 14.14). Gevolg dat verderop terugkomt: declaratierijen verdwijnen bij elke opvolgrevisie,
-- terwijl ingevulde waarden per koppeling moeten blijven leven - daarom koppelt
-- import_link_bookmark_value op bookmark_name en niet met een FK naar deze tabel.
--
-- value_scope is VERPLICHT en heeft bewust geen default (keuze 1): DEFINITION wordt bij
-- materialisatie in de afgeleide revisie vastgezet, LINK wordt per importkoppeling ingevuld. Een
-- stille default zou een per-leverancier-verschillende waarde in een gedeelde definitie kunnen
-- vastzetten, wat keuze 2 juist verbiedt.
--
-- required staat op TRUE als default: een bookmark bestaat om ingevuld te worden, en een niet
-- ingevuld verplicht veld moet blokkeren (keuze 6) in plaats van stil leeg te blijven. Een optionele
-- bookmark moet dus uitdrukkelijk als optioneel gedeclareerd worden.
--
-- allowed_values/validation_pattern zijn declaratiemetadata voor de invoervalidatie in de
-- servicelaag; de database dwingt hier enkel af dat een ENUM-bookmark zonder waardenlijst niet kan
-- bestaan (een keuzelijst zonder keuzes is altijd een configuratiefout).
--
-- owner_role blijft een vrije rolcode zonder waardecheck: CatalogImport heeft geen eigen
-- rollentabel - rechten komen uit Prodis (docs/decisions.md 2026-09-18 "opslag van
-- CatalogImport-permissies"). Een enumcheck hier zou een rollenmodel vastleggen dat nog niet bestaat.
create table import_definition_bookmark (
    id                     bigint generated by default as identity,
    definition_revision_id bigint not null,
    name                   varchar(60) not null,
    label                  varchar(200) not null,
    description            varchar(500),
    data_type              varchar(40) not null,
    value_scope            varchar(20) not null,
    owner_role             varchar(40) not null,
    required               boolean not null default true,
    default_value          varchar(500),
    allowed_values         varchar(2000),
    validation_pattern     varchar(200),
    sort_order             integer not null,
    created_at             timestamp with time zone not null,
    created_by             varchar(100),
    constraint pk_import_definition_bookmark primary key (id),
    constraint uk_import_definition_bookmark_name unique (definition_revision_id, name),
    constraint uk_import_definition_bookmark_order unique (definition_revision_id, sort_order),
    constraint fk_import_definition_bookmark_revision foreign key (definition_revision_id)
        references import_definition_revision (id),
    constraint ck_import_definition_bookmark_data_type
        check (data_type in ('TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'ENUM',
                             'SUPPLIER_REFERENCE', 'LIBRARY_REFERENCE', 'POLICY_PROFILE_REFERENCE')),
    constraint ck_import_definition_bookmark_scope
        check (value_scope in ('DEFINITION', 'LINK')),
    constraint ck_import_definition_bookmark_enum
        check (data_type <> 'ENUM' or allowed_values is not null)
);

--rollback drop table import_definition_bookmark;

-- De naamcheck staat in twee dialectvarianten omdat H2 en PostgreSQL geen gemeenschappelijke
-- regexsyntaxis hebben: H2 kent de REGEXP-operator, PostgreSQL de ~-operator, en regexp_like()
-- bestaat pas vanaf PostgreSQL 15. translate() is GEEN alternatief: in H2 verwijdert die de extra
-- tekens niet (feitelijk nagegaan), zodat een portable variant stilzwijgend niets zou controleren -
-- erger dan geen check. Beide varianten leggen dezelfde constraintnaam en dezelfde regel op:
-- BESTANDS_PREFIX mag, bad-name of 1CULTUUR niet.

--changeset catalogimport:006-1b-import-definition-bookmark-name-postgresql dbms:postgresql
--comment Naamformaat van een bookmark, PostgreSQL-variant van dezelfde regel als 006-1c.

alter table import_definition_bookmark add constraint ck_import_definition_bookmark_name
    check (name ~ '^[A-Z][A-Z0-9_]*$');

--rollback alter table import_definition_bookmark drop constraint ck_import_definition_bookmark_name;

--changeset catalogimport:006-1c-import-definition-bookmark-name-h2 dbms:h2
--comment Naamformaat van een bookmark, H2-variant van dezelfde regel als 006-1b.

alter table import_definition_bookmark add constraint ck_import_definition_bookmark_name
    check (name regexp '^[A-Z][A-Z0-9_]*$');

--rollback alter table import_definition_bookmark drop constraint ck_import_definition_bookmark_name;

--changeset catalogimport:006-2-import-definition-bookmark-usage
--comment Witte lijst van configuratieplaatsen waar een bookmark toegepast mag worden (decisions.md 2026-09-23, keuze 3).

-- Dit is een WITTE lijst, geen vrije verwijzing: een bookmark mag alleen toegepast worden op een
-- plaats die hier uitdrukkelijk toegelaten is. Een bookmark die nergens toegepast wordt, is een
-- invulveld dat niets doet; een bookmark die overal mag, is niet meer te overzien bij het
-- materialiseren.
--
-- DELIVERY_FILE_SELECTION (het BA1-voorbeeld BESTANDS_PREFIX) staat hier BEWUST NIET in
-- (decisions.md 2026-09-23 keuze 3, fase3-rules-design.md par. 2 "Important technical constraint
-- discovered"): bestandsselectie hoort bij een Leveringsconfiguratie-entiteit die nog niet bestaat.
-- Een bookmarkplaats toelaten die nergens toegepast kan worden, levert een invulveld op dat de
-- gebruiker moet invullen zonder dat het ooit effect heeft. De waarde komt er additief bij zodra
-- Leveringsconfiguratie gebouwd is.
--
-- target_hint is NOT NULL met default '' en niet nullable: in een UNIQUE constraint botsen
-- NULL-waarden niet met elkaar, zodat twee rijen (bookmark, FIELD_MAPPING_FIXED_VALUE, NULL) naast
-- elkaar zouden kunnen bestaan en de witte lijst stilzwijgend dubbel zou raken. '' betekent hier
-- "geen nadere aanduiding", en dat is precies één waarde.
create table import_definition_bookmark_usage (
    id          bigint generated by default as identity,
    bookmark_id bigint not null,
    place_kind  varchar(40) not null,
    target_hint varchar(200) not null default '',
    created_at  timestamp with time zone not null,
    constraint pk_import_definition_bookmark_usage primary key (id),
    constraint uk_import_definition_bookmark_usage unique (bookmark_id, place_kind, target_hint),
    constraint fk_import_definition_bookmark_usage_bookmark foreign key (bookmark_id)
        references import_definition_bookmark (id),
    constraint ck_import_definition_bookmark_usage_place
        check (place_kind in ('FIELD_MAPPING_FIXED_VALUE', 'RECORD_FILTER_COMPARE_VALUE',
                              'REVISION_IDENTITY_FIELD', 'REVISION_PRICE_POLICY',
                              'LINK_LIBRARY_CODE', 'LINK_SEARCH_SUPPLIER',
                              'LINK_SUPPLIER_ORGANISATION'))
);

--rollback drop table import_definition_bookmark_usage;

--changeset catalogimport:006-3-import-definition-bookmark-value
--comment DEFINITION-scope snapshot: de bookmarkwaarde zoals ze bij materialisatie in de afgeleide revisie vastgezet is (decisions.md 2026-09-23, keuze 1).

-- Materialisatie schrijft de waarde LETTERLIJK in de doelkolom van de afgeleide revisie
-- (import_field_mapping.fixed_value met value_kind 'FIXED_VALUE', import_record_filter.compare_value,
-- een identity_*_field). Zie fase3-rules-design.md par. 2, aanvullingen bij 004-2 en 004-3: voor
-- recordfilters is dat niet één van twee opties maar de enige die werkt zonder een bestaande tabel te
-- wijzigen. Deze tabel is daarom de ENIGE plek waar de herkomst van zo'n gematerialiseerde waarde nog
-- af te lezen is; zonder deze rij is achteraf niet meer vast te stellen dat een vaste waarde uit een
-- sjabloon kwam en uit welke sjabloonversie.
--
-- value_text is NOT NULL en mag '' zijn. Dat onderscheid is hier hard: '' betekent "uitdrukkelijk
-- leeg ingevuld", terwijl "niet ingevuld" wordt uitgedrukt door de AFWEZIGHEID van een rij. Een
-- nullable kolom zou die twee toestanden op één waarde laten vallen, precies de fout die de
-- aanbiedingsidentiteit elders al vermijdt (decisions.md 2026-09-18: null is niet "").
--
-- value_text is varchar(500), gelijk aan import_field_mapping.fixed_value en
-- import_record_filter.compare_value: een langere waarde zou wel opgeslagen kunnen worden maar bij
-- materialisatie niet meer in de doelkolom passen, en dan pas afbreken.
--
-- source_template_revision_id is nullable: de sjabloonrevisie is bekend bij een materialisatie uit
-- een sjabloon, maar een handmatig ingevulde waarde op een gewone definitie heeft geen bron.
create table import_definition_bookmark_value (
    id                          bigint generated by default as identity,
    definition_revision_id      bigint not null,
    bookmark_name               varchar(60) not null,
    data_type                   varchar(40) not null,
    value_text                  varchar(500) not null,
    source_template_revision_id bigint,
    filled_at                   timestamp with time zone not null,
    filled_by                   varchar(100) not null,
    constraint pk_import_definition_bookmark_value primary key (id),
    constraint uk_import_definition_bookmark_value unique (definition_revision_id, bookmark_name),
    constraint fk_import_definition_bookmark_value_revision foreign key (definition_revision_id)
        references import_definition_revision (id),
    constraint fk_import_definition_bookmark_value_template foreign key (source_template_revision_id)
        references import_definition_revision (id),
    constraint ck_import_definition_bookmark_value_data_type
        check (data_type in ('TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'ENUM',
                             'SUPPLIER_REFERENCE', 'LIBRARY_REFERENCE', 'POLICY_PROFILE_REFERENCE'))
);

--rollback drop table import_definition_bookmark_value;

--changeset catalogimport:006-4-import-link-bookmark-value
--comment LINK-scope waarde: de per importkoppeling ingevulde bookmarkwaarde (decisions.md 2026-09-23, keuze 1 en 2).

-- GEEN foreign key naar import_definition_bookmark, en dat is een uitdrukkelijke ontwerpkeuze
-- (decisions.md 2026-09-23): de declaratie hangt aan een REVISIE en verdwijnt dus bij elke
-- opvolgrevisie van het sjabloon, terwijl de koppeling blijft bestaan. Met een FK zou elke nieuwe
-- sjabloonversie de ingevulde leverancierswaarden ongeldig maken of meeslepen. De koppeling gebeurt
-- daarom op bookmark_name; data_type staat gedenormaliseerd mee zodat de waarde ook leesbaar blijft
-- wanneer de declaratie van toen niet meer bestaat (zelfde redenering als R-ISS-02 voor issuerijen).
--
-- Keerzijde die de servicelaag moet opvangen: een naam die in de nieuwe sjabloonversie niet meer
-- gedeclareerd is, blijft hier als wees staan. Dat is bewust - de waarde is auditmateriaal - maar de
-- materialisatie moet zo'n wees tonen en niet stilzwijgend toepassen.
--
-- previous_value_text/updated_at/updated_by vormen samen de wijzigingsaudit: een bookmarkwaarde
-- bepaalt mee wat er geïmporteerd en gepubliceerd wordt, dus een wijziging mag nooit alleen in een
-- logregel bestaan. De twee checks beletten een halve audit (wel tijdstip, geen naam) en een vorige
-- waarde zonder wijziging die haar verklaart.
create table import_link_bookmark_value (
    id                  bigint generated by default as identity,
    import_link_id      bigint not null,
    bookmark_name       varchar(60) not null,
    data_type           varchar(40) not null,
    value_text          varchar(500) not null,
    previous_value_text varchar(500),
    filled_at           timestamp with time zone not null,
    filled_by           varchar(100) not null,
    updated_at          timestamp with time zone,
    updated_by          varchar(100),
    constraint pk_import_link_bookmark_value primary key (id),
    constraint uk_import_link_bookmark_value unique (import_link_id, bookmark_name),
    constraint fk_import_link_bookmark_value_link foreign key (import_link_id)
        references import_link (id),
    constraint ck_import_link_bookmark_value_data_type
        check (data_type in ('TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'BOOLEAN', 'ENUM',
                             'SUPPLIER_REFERENCE', 'LIBRARY_REFERENCE', 'POLICY_PROFILE_REFERENCE')),
    constraint ck_import_link_bookmark_value_updated
        check ((updated_at is null and updated_by is null)
            or (updated_at is not null and updated_by is not null)),
    constraint ck_import_link_bookmark_value_previous
        check (previous_value_text is null or updated_at is not null)
);

--rollback drop table import_link_bookmark_value;

--changeset catalogimport:006-5-import-link-definition-usage-guard
--comment Databaseguard: een sjabloon (REUSABLE_TEMPLATE) kan nooit aan een importkoppeling hangen (decisions.md 2026-09-23, keuze 7).

-- Een sjabloon is een blauwdruk, geen live configuratie (par. 14.16). Zou een ImportLink toch aan een
-- sjabloon kunnen hangen, dan zou dat sjabloon leveringen, batches, mutaties en uiteindelijk een
-- publicatie krijgen. Keuze 7 legt die grens daarom in de DATABASE en niet enkel in de servicelaag:
-- ook een toekomstige servicebug mag dit niet kunnen.
--
-- Constructie in drie stappen, zonder ook maar één bestaande kolom aan te raken:
--   1. import_definition krijgt een extra UNIQUE (id, usage_type). Functioneel overbodig (id is al
--      pk), maar een samengestelde foreign key vereist een unieke sleutel op exact die twee kolommen.
--   2. import_link krijgt een NIEUWE kolom definition_usage_type met default 'OWN_DEFINITION', zodat
--      alle bestaande rijen geldig blijven zonder datamigratie.
--   3. de samengestelde FK (import_definition_id, definition_usage_type) -> (id, usage_type) plus de
--      check definition_usage_type = 'OWN_DEFINITION' maken samen de uitspraak hard: de gekoppelde
--      definitie MOET usage_type 'OWN_DEFINITION' hebben. De check alleen zou niets zeggen over de
--      definitie; de FK alleen zou ook REUSABLE_TEMPLATE toelaten.
--
-- Nevengevolg dat we bewust willen: zolang er een ImportLink naar een definitie wijst, kan die
-- definitie niet meer op REUSABLE_TEMPLATE gezet worden - de FK weigert dat. Een live definitie
-- achteraf tot sjabloon ombouwen terwijl ze leveringen ontvangt, was toch al nooit de bedoeling.
--
-- De kolom is BEWUST NIET gemapt op de ImportLink-entiteit: ze draagt altijd dezelfde waarde en heeft
-- geen businessbetekenis in Java. Hibernate laat een niet-gemapte kolom bij het invoegen weg, waarna
-- de default hem vult, en ddl-auto: validate klaagt niet over een extra kolom in de tabel.
--
-- Migratierisico, uitdrukkelijk: bestaat er in een omgeving al een import_link naar een
-- REUSABLE_TEMPLATE-definitie, dan FAALT deze changeset op de FK. Dat is de bedoeling - zo'n rij is
-- precies de toestand die de guard verbiedt en moet met de hand rechtgezet worden, niet stil
-- omgezet.
alter table import_definition add constraint uk_import_definition_id_usage unique (id, usage_type);

alter table import_link add column definition_usage_type varchar(40) not null default 'OWN_DEFINITION';

alter table import_link add constraint ck_import_link_definition_usage_type
    check (definition_usage_type = 'OWN_DEFINITION');

alter table import_link add constraint fk_import_link_definition_usage
    foreign key (import_definition_id, definition_usage_type)
    references import_definition (id, usage_type);

--rollback alter table import_link drop constraint fk_import_link_definition_usage;
--rollback alter table import_link drop constraint ck_import_link_definition_usage_type;
--rollback alter table import_link drop column definition_usage_type;
--rollback alter table import_definition drop constraint uk_import_definition_id_usage;

--changeset catalogimport:006-6-import-batch-bookmark-values-hash
--comment Reproduceerbaarheid: vingerafdruk van de bookmarkwaarden waarmee een batch gedraaid heeft (decisions.md 2026-09-23, keuze 5).

-- Additieve kolom op de BESTAANDE tabel import_batch (aangemaakt in 002-import-screening-core.sql,
-- dat ongewijzigd blijft). Nullable: elke batch van vóór het sjabloonmechanisme, en elke batch van een
-- koppeling zonder bookmarks, heeft geen waarde - NULL betekent hier "geen bookmarkwaarden van
-- toepassing of nog niet vastgesteld", nooit stil "leeg".
--
-- Waarom dit nodig is: de gematerialiseerde bookmarkwaarden bepalen mee wat er gelezen, gefilterd en
-- gepubliceerd wordt. Zonder deze vingerafdruk is achteraf niet meer te bewijzen met welke
-- invulwaarden een levering gescreend is, terwijl de revisiehash dat voor de rest van de configuratie
-- wél doet.
--
-- NOG NIET GEBOUWD (servicelaag, uitdrukkelijk buiten deze Fase 1-stap): het berekenen en vullen van
-- deze kolom, en de andere helft van keuze 5 - een LINK-scope bookmarkwaarde die niet meer wijzigbaar
-- is zolang de koppeling een open (niet-terminale) batch heeft.
alter table import_batch add column bookmark_values_hash ${hash.type};

--rollback alter table import_batch drop column bookmark_values_hash;
