--liquibase formatted sql

-- Fase 5-PUB (deel a), bouwstap 5P-1 (docs/design/fase5-pub-design.md par. 1 en 6; docs/decisions.md
-- 2026-09-26 "5-PUB (deel a): ontwerp bindend"). Volledig ADDITIEF naast 001-007, die ongewijzigd blijven.
-- Enkel schema: het vullen bij bevriezen (5P-2) en het berekenen van snapshot_hash (5P-3) volgen later.
-- Geen backfill en geen default: reeds bevroren bundels houden snapshot_hash NULL (NO_SNAPSHOT).
-- Geen *_by_subject-kolommen: de ondertekenaar staat al op publication_bundle.frozen_by(_subject).

--changeset catalogimport:008-1-publication-bundle-snapshot
--comment Bundelsnapshot: een rij per te publiceren mutatie, bewaard bij het bevriezen (design par. 1).

-- batch_id en import_link_id zijn gedenormaliseerde herkomstverwijzingen (net als publication_bundle_batch);
-- enkel bundle_id en mutation_id zijn foreign keys. description_state houdt "niet gemapt", "gemapt maar
-- leeg" en "waarde" uit elkaar (zelfde patroon als import_mutation.identity_discount_state).
-- De twee unique-constraints dekken ook de opzoekingen op mutation_id en (bundle_id, ...): geen extra index.
create table publication_bundle_snapshot (
    id                bigint generated by default as identity,
    bundle_id         bigint not null,
    mutation_id       bigint not null,
    batch_id          bigint not null,
    import_link_id    bigint not null,
    source_row_number bigint not null,
    description       varchar(1000),
    description_state varchar(20) not null,
    created_at        timestamp with time zone not null,
    constraint pk_publication_bundle_snapshot primary key (id),
    constraint fk_publication_bundle_snapshot_bundle foreign key (bundle_id)
        references publication_bundle (id),
    constraint fk_publication_bundle_snapshot_mutation foreign key (mutation_id)
        references import_mutation (id),
    constraint uk_publication_bundle_snapshot_mutation unique (mutation_id),
    constraint uk_publication_bundle_snapshot_bundle_mutation unique (bundle_id, mutation_id),
    constraint ck_publication_bundle_snapshot_description_state check (description_state in
        ('VALUE', 'EMPTY', 'NOT_MAPPED'))
);

--rollback drop table publication_bundle_snapshot;

--changeset catalogimport:008-2-publication-bundle-snapshot-price
--comment Prijscomponenten van de bundelsnapshot: exacte kopie van import_candidate_price, zonder herberekening of afronding (design par. 1).

-- Exact dezelfde kolomtypes als import_candidate_price (004-5). Geen on delete cascade: een snapshot is
-- auditmateriaal en wordt nooit verwijderd (zelfde keuze als catalog_source_state_price, 004-6); enkel de
-- staging-tabellen gebruiken cascade omdat die een op te ruimen geheel vormen.
create table publication_bundle_snapshot_price (
    snapshot_id    bigint not null,
    component_code varchar(20) not null,
    source_amount  numeric(24,6),
    percentage     numeric(24,12),
    currency       varchar(3),
    status         varchar(30) not null,
    constraint pk_publication_bundle_snapshot_price primary key (snapshot_id, component_code),
    constraint fk_publication_bundle_snapshot_price_snapshot foreign key (snapshot_id)
        references publication_bundle_snapshot (id)
);

--rollback drop table publication_bundle_snapshot_price;

--changeset catalogimport:008-3-publication-bundle-snapshot-hash
--comment Snapshot-hash en specificatieversie op de bundel; nullable, zonder default en zonder backfill (design par. 1).

-- snapshot_hash gebruikt ${hash.type}, zoals content_hash (005-1). NULL = geen snapshot (bundel van voor 5-PUB).
alter table publication_bundle add column snapshot_hash ${hash.type};
alter table publication_bundle add column snapshot_spec_version varchar(10);

--rollback alter table publication_bundle drop column snapshot_spec_version;
--rollback alter table publication_bundle drop column snapshot_hash;
