--liquibase formatted sql

-- Fase 5-PUB (deel a), bouwstap 5P-6 (docs/design/fase5-pub-design.md par. 3 en 6; docs/decisions.md
-- 2026-09-26 "5-PUB (deel a): ontwerp bindend"). Volledig ADDITIEF naast 001-008. Enkel schema: de
-- service die runs aanmaakt en de statusovergangen uitvoert volgt in 5P-7.

--changeset catalogimport:009-1-publication-run
--comment Publicatierun: een poging om een bevroren bundel te publiceren; in 5-PUB-a enkel SIMULATION (design par. 3).

-- target_mode heeft BEWUST GEEN default (zelfde reden als publication_bundle.target_mode, 005-1).
-- SIMULATED = artefact geschreven, GEEN operationeel effect; nooit te verwarren met APPLIED.
-- Tellers en artefactvelden zijn nullable: NULL = niet vastgesteld, nooit stil 0. Welke artefactvelden
-- samen gevuld moeten zijn bij SIMULATED is een bedrijfsregel van de service (5P-7), geen schemacheck.
--
-- artifact_sha256 is varchar(64) (hex), zoals de andere hex-hashkolommen (001: *_config_hash varchar(64));
-- bundle_content_hash/snapshot_hash/payload_hash zijn ${hash.type} zoals publication_bundle.content_hash.
-- requested_by is NOT NULL: geen koppelcheck voor requested_by_subject (zelfde redenering als
-- created_by_subject in 007-2).
--
-- active_marker is TRUE zolang de run niet-terminaal is en NULL bij SIMULATED/FAILED (NULL-markertruc van
-- uk_import_batch_open, 002-2): hoogstens een niet-terminale run per bundel, ook bij gelijktijdige
-- aanvragen. De statussen die 5-PUB-a nooit zet gelden voorlopig als niet-terminaal; 5-PUB-b/c herziet
-- ck_publication_run_marker wanneer zij gebruikt worden.
create table publication_run (
    id                    bigint generated by default as identity,
    bundle_id             bigint not null,
    target_mode           varchar(30) not null,
    attempt               integer not null default 1,
    status                varchar(30) not null,
    requested_by          varchar(100) not null,
    requested_by_subject  varchar(255),
    requested_at          timestamp with time zone not null,
    started_at            timestamp with time zone,
    finished_at           timestamp with time zone,
    bundle_content_hash   ${hash.type} not null,
    snapshot_hash         ${hash.type},
    payload_hash          ${hash.type},
    artifact_reference    varchar(500),
    artifact_sha256       varchar(64),
    artifact_byte_size    bigint,
    row_count             bigint,
    incomplete_row_count  bigint,
    failure_code          varchar(60),
    failure_message       varchar(1000),
    idempotency_key       varchar(200) not null,
    active_marker         boolean,
    constraint pk_publication_run primary key (id),
    constraint fk_publication_run_bundle foreign key (bundle_id) references publication_bundle (id),
    constraint uk_publication_run_idempotency unique (idempotency_key),
    constraint uk_publication_run_active unique (bundle_id, active_marker),
    constraint ck_publication_run_target_mode check (target_mode in
        ('SIMULATION', 'TRIAL_LIBRARY', 'PRODUCTION')),
    constraint ck_publication_run_status check (status in
        ('REQUESTED', 'PREPARING', 'SIMULATED', 'FAILED', 'WAITING_FOR_TARGET_CONTRACT',
         'READY_FOR_DELIVERY', 'WRITTEN_TO_PSIMPORT', 'RESULT_UNKNOWN', 'APPLIED', 'REJECTED_BY_PRODIS',
         'RECOVERY_REQUIRED')),
    -- FALSE zou een derde toestand invoeren die de NULL-markertruc uitschakelt (zie 005-2).
    constraint ck_publication_run_marker check (active_marker is null or active_marker = true),
    -- Niet-terminaal: marker TRUE. Terminaal (SIMULATED, FAILED): marker NULL. Geen tussenvorm.
    constraint ck_publication_run_marker_status check (
        (status in ('SIMULATED', 'FAILED') and active_marker is null)
        -- "is true" en niet "= true": een CHECK slaagt bij NULL, dus "= true" liet een niet-terminale run met
        -- marker NULL door en schakelde daarmee de NULL-markertruc (hoogstens één actieve run) uit.
        or (status not in ('SIMULATED', 'FAILED') and active_marker is true)),
    -- Een terminale run draagt altijd zijn eindtijdstip; een mislukte run altijd een foutcode.
    constraint ck_publication_run_finished check (status not in ('SIMULATED', 'FAILED')
        or finished_at is not null),
    constraint ck_publication_run_failed check (status <> 'FAILED' or failure_code is not null)
);

create index idx_publication_run_bundle on publication_run (bundle_id);

--rollback drop index idx_publication_run_bundle;
--rollback drop table publication_run;
