--liquibase formatted sql

-- Behandelgeval (docs/design/issue-case-design.md, spoor S2-0 uit docs/decisions.md 2026-09-27
-- "Heropening D14-vervolg"). Bouwstap S2-B1: enkel schema, geen gedrag. Volledig ADDITIEF naast
-- 001-011, die ongewijzigd blijven.
--
-- Waarom een eigen enum-achtige statuswaarde (varchar + check) en niet IssueHandlingStatus
-- hergebruikt: die bevat ACCEPTED_FOR_BATCH/ACCEPTED_BY_RULE, precies wat D3 verbiedt (design par. 0).
-- ck_issue_case_status laat daarom uitsluitend AWAITING_REVIEW/CORRECTED/REJECTED/AUTO_RESOLVED toe -
-- geen ACCEPTED_*, geen DETECTED.

--changeset catalogimport:012-1-issue-case
--comment Het behandelgeval: één rij per (import_link_id, issue_code, signature) - de observatie-eenheid van een terugkerend probleem (design par. 1, R-CASE-01).

-- Identiteit (D1): (import_link_id, issue_code, signature) is uniek, dus herhaling van hetzelfde
-- probleem creëert nooit een tweede geval (R-CASE-01).
--
-- severity/issue_domain/control_level/impact_scope/incident_kind zijn gedenormaliseerd bij aanmaak
-- uit de eerste groep en worden daarna nooit bijgewerkt: de classificatie mag niet van de wijzigbare
-- foutcodecatalogus afhangen (zelfde motivatie als import_issue_group, R-ISS-02).
--
-- observation_count/total_occurrence_count/first_seen_at/last_seen_at worden altijd herberekend,
-- nooit "+1" - net als een teller op import_batch, nooit stil 0 wanneer niet gemeten.
--
-- status_changed_at/status_changed_by/status_changed_by_subject volgen het *_by/*_by_subject-paar
-- van changeset 007 (OIDC-subject nullable = geen geverifieerde identiteit, of systeemheropening).
create table issue_case (
    id                          bigint generated by default as identity,
    import_link_id              bigint not null,
    issue_code                  varchar(60) not null,
    signature                   varchar(300) not null,
    severity                    varchar(20) not null,
    issue_domain                varchar(40) not null,
    control_level               varchar(20) not null,
    impact_scope                varchar(20) not null,
    incident_kind               varchar(30) not null,
    price_component_code        varchar(20),
    reference_type              varchar(30),
    status                      varchar(30) not null,
    observation_count           bigint not null,
    total_occurrence_count      bigint not null,
    first_seen_at               timestamp with time zone not null,
    last_seen_at                timestamp with time zone not null,
    first_seen_batch_id         bigint not null,
    last_seen_batch_id          bigint not null,
    last_seen_revision_id       bigint not null,
    reopen_count                integer not null default 0,
    status_reason               varchar(500),
    status_changed_at           timestamp with time zone,
    status_changed_by           varchar(100),
    status_changed_by_subject   varchar(255),
    decision_revision_id        bigint,
    created_at                  timestamp with time zone not null,
    updated_at                  timestamp with time zone not null,
    constraint pk_issue_case primary key (id),
    constraint uk_issue_case_identity unique (import_link_id, issue_code, signature),
    constraint fk_issue_case_import_link foreign key (import_link_id) references import_link (id),
    constraint fk_issue_case_first_batch foreign key (first_seen_batch_id) references import_batch (id),
    constraint fk_issue_case_last_batch foreign key (last_seen_batch_id) references import_batch (id),
    constraint fk_issue_case_last_revision foreign key (last_seen_revision_id)
        references import_definition_revision (id),
    constraint fk_issue_case_decision_revision foreign key (decision_revision_id)
        references import_definition_revision (id),
    -- Geen ACCEPTED_*, geen DETECTED (D3): het behandelgeval laat per definitie niets door.
    constraint ck_issue_case_status
        check (status in ('AWAITING_REVIEW', 'CORRECTED', 'REJECTED', 'AUTO_RESOLVED')),
    constraint ck_issue_case_status_change
        check (status_changed_at is null or status_reason is not null),
    constraint ck_issue_case_decided
        check (status = 'AWAITING_REVIEW' or (status_changed_at is not null and status_reason is not null)),
    constraint ck_issue_case_status_subject
        check (status_changed_by_subject is null or status_changed_by is not null),
    -- Een geval zonder waarnemingen mag alleen bestaan als er al een menselijke actie op staat
    -- (herstelpad ScreeningRecoveryService, S2-B1b).
    constraint ck_issue_case_observations
        check (observation_count >= 0 and (observation_count > 0 or status_changed_at is not null))
);

create index idx_issue_case_link_status on issue_case (import_link_id, status);
create index idx_issue_case_status_last_seen on issue_case (status, last_seen_at);

--rollback drop index idx_issue_case_status_last_seen;
--rollback drop index idx_issue_case_link_status;
--rollback drop table issue_case;

--changeset catalogimport:012-2-issue-case-event
--comment Append-only auditregister van het behandelgeval (design par. 1/§2, R-CASE-04). Nooit bijgewerkt, nooit verwijderd - patroon publication_decision (005-3).

-- Zonder deze tabel zou een systeemheropening de afwijzingsreden van de mens overschrijven: dat botst
-- met BA §13 r.1006 ("Iedere actie bewaart gebruiker, tijd, reden") en met AGENT.md Fase 4.
--
-- previous_status is null enkel bij CREATED (er is nog geen vorige status). source bepaalt of
-- changed_by/changed_by_subject gevuld mogen zijn: HUMAN draagt altijd een naam, SYSTEM nooit.
create table issue_case_event (
    id                        bigint generated by default as identity,
    issue_case_id             bigint not null,
    event_kind                varchar(30) not null,
    previous_status           varchar(30),
    new_status                varchar(30) not null,
    reason                    varchar(500) not null,
    source                    varchar(20) not null,
    changed_by                varchar(100),
    changed_by_subject        varchar(255),
    changed_at                timestamp with time zone not null,
    observation_batch_id      bigint,
    constraint pk_issue_case_event primary key (id),
    constraint fk_issue_case_event_case foreign key (issue_case_id) references issue_case (id),
    constraint fk_issue_case_event_batch foreign key (observation_batch_id) references import_batch (id),
    constraint ck_issue_case_event_kind check (event_kind in ('CREATED', 'STATUS_CHANGE')),
    constraint ck_issue_case_event_status check (
        (previous_status is null or previous_status in ('AWAITING_REVIEW', 'CORRECTED', 'REJECTED', 'AUTO_RESOLVED'))
        and new_status in ('AWAITING_REVIEW', 'CORRECTED', 'REJECTED', 'AUTO_RESOLVED')
    ),
    constraint ck_issue_case_event_previous
        check (event_kind <> 'CREATED' or previous_status is null),
    constraint ck_issue_case_event_source
        check ((source = 'HUMAN' and changed_by is not null)
            or (source = 'SYSTEM' and changed_by is null and changed_by_subject is null)),
    constraint ck_issue_case_event_subject
        check (changed_by_subject is null or changed_by is not null)
);

-- Sortering op id, geen sequence_no (patroon publication_decision): het chronologisch verloop van
-- één geval, in insertievolgorde.
create index idx_issue_case_event_case on issue_case_event (issue_case_id, id);

--rollback drop index idx_issue_case_event_case;
--rollback drop table issue_case_event;

--changeset catalogimport:012-3-import-issue-group-case-link
--comment Koppeling van een issuegroep aan haar behandelgeval (design par. 1). Additief, nullable, geen backfill: bestaande groepen van vóór deze changeset krijgen geen geval.

alter table import_issue_group add column issue_case_id bigint;

alter table import_issue_group add constraint fk_import_issue_group_case
    foreign key (issue_case_id) references issue_case (id);

create index idx_import_issue_group_case on import_issue_group (issue_case_id);

--rollback drop index idx_import_issue_group_case;
--rollback alter table import_issue_group drop constraint fk_import_issue_group_case;
--rollback alter table import_issue_group drop column issue_case_id;
