--liquibase formatted sql

-- Versleutelde opslag van externe credentials (SFTP-wachtwoorden): bouwstap K-2a van
-- docs/design/leveringsconfiguratie-design.md par. 10 en docs/design/credentials-sleutelbeheer-design.md
-- par. 5 (definitief datamodel), beslissingslog 2026-09-29 (V1-V8, L1-L8, A6, A7, A19). Enkel schema, geen
-- API. Volledig ADDITIEF naast 001-012, die ongewijzigd blijven.
--
-- Wat hier NOOIT staat: een secret in zuivere tekst of een hash ervan. ciphertext is de uitvoer van
-- SecretsService (v1:<keyId>:<base64(nonce||ciphertext+tag)>, AES-256-GCM); de associated data bindt die
-- waarde aan credential_ref en secret_kind, zodat een ciphertext niet naar een andere rij verplaatst kan
-- worden.
--
-- Conventies (001/007/012): id bigint generated by default as identity; timestamp with time zone;
-- *_by varchar(100) + *_by_subject varchar(255) met koppelcheck bij een nullable *_by; reden varchar(500);
-- append-only eventtabel met source HUMAN/SYSTEM waarbij SYSTEM => changed_by/changed_by_subject null
-- (patroon 012-issue-case.sql r.116-120). Subjectkolommen zijn audit-only: geen index.

--changeset catalogimport:013-1-external-credential
--comment Een versleuteld opgeslagen credential van een externe bron, DB-afgedwongen aan één host gebonden (credentials-design par. 5.1, leveringsconfiguratie-design par. 3.1, L4a).

-- credential_ref wordt vóór de insert in Java gegenereerd (A19): de associated data van AES-GCM heeft
-- hem nodig, en een identity-id bestaat pas na de insert (credentials-design par. 3).
--
-- status kent enkel ACTIVE/REVOKED; UNDECRYPTABLE is afgeleid (de ciphertext ontsleutelt niet), nooit
-- opgeslagen (A6). ciphertext en encryption_key_id zijn nullable: intrekken is de crypto-shred
-- (par. 5.4) en zet beide op null. De drie statuschecks houden dat consistent:
--   * ck_external_credential_secret_present: ACTIVE <=> er is een ciphertext;
--   * ck_external_credential_key_id: encryption_key_id is gevuld exact wanneer ciphertext gevuld is;
--   * ck_external_credential_revoked: een ingetrokken credential draagt altijd een reden.
--
-- uk_external_credential_host_binding (id, secret_kind, bound_host) is het doel van de samengestelde FK
-- vanuit connection_profile_version (changeset 014, LC-1): een profielversie met een andere host dan de
-- credential kan daardoor niet bestaan (Ontdekking 2 van het leveringsconfiguratie-ontwerp).
create table external_credential (
    id                          bigint generated by default as identity,
    credential_ref              uuid not null,
    label                       varchar(200) not null,
    secret_kind                 varchar(40) not null,
    bound_host                  varchar(255) not null,
    ciphertext                  text,
    encryption_key_id           varchar(32),
    status                      varchar(20) not null,
    secret_updated_at           timestamp with time zone,
    secret_updated_by           varchar(100),
    secret_updated_by_subject   varchar(255),
    created_at                  timestamp with time zone not null,
    created_by                  varchar(100) not null,
    created_by_subject          varchar(255),
    revoked_at                  timestamp with time zone,
    revoked_by                  varchar(100),
    revoked_by_subject          varchar(255),
    revoked_reason              varchar(500),
    constraint pk_external_credential primary key (id),
    constraint uk_external_credential_ref unique (credential_ref),
    constraint uk_external_credential_host_binding unique (id, secret_kind, bound_host),
    -- SSH_PRIVATE_KEY is gereserveerd; v1 kent enkel wachtwoordauthenticatie (A5).
    constraint ck_external_credential_secret_kind
        check (secret_kind in ('SFTP_PASSWORD', 'SSH_PRIVATE_KEY')),
    constraint ck_external_credential_status check (status in ('ACTIVE', 'REVOKED')),
    constraint ck_external_credential_secret_present check ((status = 'ACTIVE') = (ciphertext is not null)),
    constraint ck_external_credential_key_id check ((ciphertext is null) = (encryption_key_id is null)),
    constraint ck_external_credential_revoked check (status <> 'REVOKED' or revoked_reason is not null),
    constraint ck_external_credential_secret_updated_subject
        check (secret_updated_by_subject is null or secret_updated_by is not null),
    constraint ck_external_credential_revoked_subject
        check (revoked_by_subject is null or revoked_by is not null)
);

--rollback drop table external_credential;

--changeset catalogimport:013-2-external-credential-event
--comment Append-only auditregister van een credential (credentials-design par. 5.2). Nooit bijgewerkt, nooit verwijderd; nooit een waarde of hash van het secret.

-- Sortering op id, geen sequence_no (patroon issue_case_event, 012-2). previous_key_id/new_key_id zijn
-- sleutel-ID's, nooit sleutelmateriaal:
--   * CREATED: er is nog geen vorige sleutel (ck_external_credential_event_created, analoog aan
--     ck_issue_case_event_previous);
--   * REENCRYPTED: de herversleutelbatch (K-2b, R2a) legt altijd beide sleutel-ID's vast (par. 5.2);
--   * REVOKED: na de crypto-shred bestaat er geen nieuwe sleutel.
-- source bepaalt of changed_by/changed_by_subject gevuld mogen zijn: HUMAN draagt altijd een naam, SYSTEM
-- nooit (ook niet de tekst "system").
create table external_credential_event (
    id                    bigint generated by default as identity,
    credential_id         bigint not null,
    event_kind            varchar(30) not null,
    reason                varchar(500) not null,
    source                varchar(20) not null,
    changed_by            varchar(100),
    changed_by_subject    varchar(255),
    changed_at            timestamp with time zone not null,
    previous_key_id       varchar(32),
    new_key_id            varchar(32),
    constraint pk_external_credential_event primary key (id),
    constraint fk_external_credential_event_credential foreign key (credential_id)
        references external_credential (id),
    constraint ck_external_credential_event_kind
        check (event_kind in ('CREATED', 'REPLACED', 'REVOKED', 'REENCRYPTED')),
    constraint ck_external_credential_event_source
        check ((source = 'HUMAN' and changed_by is not null)
            or (source = 'SYSTEM' and changed_by is null and changed_by_subject is null)),
    constraint ck_external_credential_event_subject
        check (changed_by_subject is null or changed_by is not null),
    constraint ck_external_credential_event_created
        check (event_kind <> 'CREATED' or previous_key_id is null),
    constraint ck_external_credential_event_reencrypted
        check (event_kind <> 'REENCRYPTED' or (previous_key_id is not null and new_key_id is not null)),
    constraint ck_external_credential_event_revoked
        check (event_kind <> 'REVOKED' or new_key_id is null)
);

create index idx_external_credential_event_credential on external_credential_event (credential_id, id);

--rollback drop index idx_external_credential_event_credential;
--rollback drop table external_credential_event;

--changeset catalogimport:013-3-secret-key-check
--comment Controlewaarde per sleutel: hoort deze sleutel bij deze database (credentials-design par. 5.3, A7, V7).

-- check_value is een vaste, bekende tekst versleuteld met de sleutel key_id onder de eigen associated
-- data catalogimport|secret_key_check|<keyId>|v1 (niet die van een credential). Bij het opstarten
-- ontsleutelt SecretKeyCheckVerifier elke geconfigureerde sleutel hiertegen: lukt dat niet, dan start
-- de applicatie niet (een sleutel met dezelfde ID maar ander materiaal hoort niet bij deze database).
-- Een rij wordt nooit bijgewerkt: ander materiaal onder dezelfde ID is precies wat gedetecteerd moet worden.
create table secret_key_check (
    key_id        varchar(32) not null,
    check_value   text not null,
    created_at    timestamp with time zone not null,
    constraint pk_secret_key_check primary key (key_id)
);

--rollback drop table secret_key_check;

--changeset catalogimport:013-4-bound-host-normalized
--comment DB-afgedwongen genormaliseerde bound_host (credentials-design par. 5.1, beslissingslog 2026-09-29 K-2a (b)); additief, 013-1 blijft ongewijzigd.

-- De host-binding (uk_external_credential_host_binding, L4a) vergelijkt strings exact. Een host die enkel in
-- hoofdletters, met een punt achteraan of met spaties verschilt, zou een credential aan "dezelfde" host
-- kunnen binden onder een andere spelling. Daarom weigert de database alles wat niet genormaliseerd is:
-- niet leeg (na trim), gelijk aan lower(), geen punt achteraan en geen enkele witruimte. Normaliseren zelf
-- hoort in de CredentialService (K-3); hier wordt enkel geweigerd.
alter table external_credential
    add constraint ck_external_credential_bound_host_normalized
    check (length(btrim(bound_host)) > 0
        and bound_host = lower(bound_host)
        and right(bound_host, 1) <> '.'
        and bound_host !~ '[[:space:]]');

--rollback alter table external_credential drop constraint ck_external_credential_bound_host_normalized;
