--liquibase formatted sql

-- Verbindingsprofiel en Leveringsconfiguratie (SFTP) met onveranderlijke versierijen: bouwstap LC-1 van
-- docs/design/leveringsconfiguratie-design.md par. 3.2 en 10, beslissingslog 2026-09-29 (L1-L8, A3, A11, A17).
-- Enkel schema, geen API. Volledig ADDITIEF naast 001-013, die ongewijzigd blijven; de enige aanraking van een
-- bestaande tabel is één nullable kolom op catalog_import_task (014-7).
--
-- Onveranderlijkheid (L3): een versierij (connection_profile_version, delivery_configuration_version en haar
-- voorwaarden) wijzigt nooit; een wijziging is een nieuwe versie. Dat wordt in JPA afgedwongen (geen setters,
-- updatable = false op elke kolom), niet met een databasetrigger: het project kent geen triggers en de
-- append-only tabellen (012-2, 013-2) volgen hetzelfde patroon.
--
-- Conventies (001/007/012/013): id bigint generated by default as identity; timestamp with time zone;
-- *_by varchar(100) + *_by_subject varchar(255) met koppelcheck subject => naam; append-only eventtabel met
-- source HUMAN/SYSTEM waarbij SYSTEM => changed_by/changed_by_subject null (patroon 012-2 en 013-2).
-- Subjectkolommen zijn audit-only: geen index.

--changeset catalogimport:014-1-connection-profile
--comment De kop van een verbindingsprofiel: stabiele code en naam; de eigenlijke verbindingsgegevens staan in de onveranderlijke versies (leveringsconfiguratie-design par. 3.2).

create table connection_profile (
    id                    bigint generated by default as identity,
    code                  varchar(50) not null,
    name                  varchar(200) not null,
    protocol              varchar(20) not null,
    active                boolean not null,
    created_at            timestamp with time zone not null,
    created_by            varchar(100) not null,
    created_by_subject    varchar(255),
    updated_at            timestamp with time zone not null,
    constraint pk_connection_profile primary key (id),
    constraint uk_connection_profile_code unique (code),
    constraint ck_connection_profile_protocol check (protocol in ('SFTP')),
    constraint ck_connection_profile_created_subject
        check (created_by_subject is null or created_by is not null)
);

--rollback drop table connection_profile;

--changeset catalogimport:014-2-connection-profile-version
--comment Onveranderlijke versie van een verbindingsprofiel; de samengestelde FK naar external_credential maakt een credential van een andere host onmogelijk (L4a, Ontdekking 2).

-- De samengestelde FK (credential_id, credential_secret_kind, credential_host) verwijst naar
-- uk_external_credential_host_binding (id, secret_kind, bound_host) uit 013-1. Samen met
-- ck_connection_profile_version_credential_host (credential_host = host) kan een profielversie met een eigen
-- host en de credential van een andere host niet bestaan: het wachtwoord kan dus nooit naar een andere server
-- gestuurd worden dan waaraan het gebonden is. De auth_method-checks houden de soort credential in lijn met de
-- gekozen authenticatie (v1 gebruikt enkel PASSWORD, A5; PRIVATE_KEY blijft gereserveerd).
--
-- host_key_algorithm/host_key_fingerprint_sha256 zijn de verplichte vastgepinde hostsleutel (L5). host volgt
-- dezelfde normalisatiecheck als external_credential.bound_host (013-4): niet leeg, kleine letters, geen punt
-- achteraan, geen witruimte. Normaliseren zelf hoort in de service (LC-2).
--
-- config_hash (varchar(64), hex) is verplicht: de service berekent hem bij elke nieuwe versie zodat een
-- identieke inhoud herkend wordt. based_on_version_id verwijst naar de versie waarop deze is gebaseerd (null bij
-- de eerste versie).
create table connection_profile_version (
    id                              bigint generated by default as identity,
    connection_profile_id           bigint not null,
    version_number                  integer not null,
    host                            varchar(255) not null,
    port                            integer not null default 22,
    username                        varchar(200) not null,
    auth_method                     varchar(20) not null,
    credential_id                   bigint not null,
    credential_secret_kind          varchar(40) not null,
    credential_host                 varchar(255) not null,
    host_key_algorithm              varchar(40) not null,
    host_key_fingerprint_sha256     varchar(100) not null,
    based_on_version_id             bigint,
    change_reason                   varchar(500),
    config_hash                     varchar(64) not null,
    created_at                      timestamp with time zone not null,
    created_by                      varchar(100) not null,
    created_by_subject              varchar(255),
    constraint pk_connection_profile_version primary key (id),
    constraint uk_connection_profile_version_number unique (connection_profile_id, version_number),
    constraint fk_connection_profile_version_profile foreign key (connection_profile_id)
        references connection_profile (id),
    constraint fk_connection_profile_version_credential foreign key (credential_id, credential_secret_kind, credential_host)
        references external_credential (id, secret_kind, bound_host),
    constraint fk_connection_profile_version_based_on foreign key (based_on_version_id)
        references connection_profile_version (id),
    constraint ck_connection_profile_version_number check (version_number >= 1),
    constraint ck_connection_profile_version_port check (port between 1 and 65535),
    constraint ck_connection_profile_version_auth_method check (auth_method in ('PASSWORD', 'PRIVATE_KEY')),
    constraint ck_connection_profile_version_credential_host check (credential_host = host),
    constraint ck_connection_profile_version_auth_password
        check ((auth_method = 'PASSWORD') = (credential_secret_kind = 'SFTP_PASSWORD')),
    constraint ck_connection_profile_version_auth_key
        check ((auth_method = 'PRIVATE_KEY') = (credential_secret_kind = 'SSH_PRIVATE_KEY')),
    constraint ck_connection_profile_version_host_normalized
        check (length(btrim(host)) > 0
            and host = lower(host)
            and right(host, 1) <> '.'
            and host !~ '[[:space:]]'),
    constraint ck_connection_profile_version_username check (length(btrim(username)) > 0),
    constraint ck_connection_profile_version_host_key
        check (length(btrim(host_key_algorithm)) > 0 and length(btrim(host_key_fingerprint_sha256)) > 0),
    constraint ck_connection_profile_version_created_subject
        check (created_by_subject is null or created_by is not null)
);

create index idx_connection_profile_version_credential on connection_profile_version (credential_id);
create index idx_connection_profile_version_based_on on connection_profile_version (based_on_version_id);

--rollback drop index idx_connection_profile_version_based_on;
--rollback drop index idx_connection_profile_version_credential;
--rollback drop table connection_profile_version;

--changeset catalogimport:014-3-delivery-configuration
--comment De kop van een Leveringsconfiguratie: stabiele code en naam; de ophaalinstellingen staan in de onveranderlijke versies (leveringsconfiguratie-design par. 3.2).

create table delivery_configuration (
    id                    bigint generated by default as identity,
    code                  varchar(50) not null,
    name                  varchar(200) not null,
    acquisition_kind      varchar(20) not null,
    active                boolean not null,
    created_at            timestamp with time zone not null,
    created_by            varchar(100) not null,
    created_by_subject    varchar(255),
    updated_at            timestamp with time zone not null,
    constraint pk_delivery_configuration primary key (id),
    constraint uk_delivery_configuration_code unique (code),
    constraint ck_delivery_configuration_acquisition_kind check (acquisition_kind in ('SFTP')),
    constraint ck_delivery_configuration_created_subject
        check (created_by_subject is null or created_by is not null)
);

--rollback drop table delivery_configuration;

--changeset catalogimport:014-4-delivery-configuration-version
--comment Onveranderlijke versie van een Leveringsconfiguratie (L3): profielversie, map, bestandskeuze, ouderdoms- en groottegrens, actie na ophalen (enkel LEAVE, A3).

-- remote_directory: absoluut, zonder '..' (A17) - dat controleert de service. min_file_age_seconds en
-- max_file_bytes zijn verplicht (A12: defaults 300 s en 1 GB worden door de service ingevuld, nooit stil door
-- de database). post_fetch_action laat in v1 enkel LEAVE toe (A3): een verbreding is een latere additieve check.
-- Servicecontrole (niet in de database): ALL_FILES = geen voorwaarden; CONDITIONS = minstens één voorwaarde.
create table delivery_configuration_version (
    id                              bigint generated by default as identity,
    delivery_configuration_id       bigint not null,
    version_number                  integer not null,
    connection_profile_version_id   bigint not null,
    remote_directory                varchar(500) not null,
    selection_mode                  varchar(20) not null,
    min_file_age_seconds            integer not null,
    max_file_bytes                  bigint not null,
    post_fetch_action               varchar(20) not null,
    based_on_version_id             bigint,
    change_reason                   varchar(500),
    config_hash                     varchar(64) not null,
    created_at                      timestamp with time zone not null,
    created_by                      varchar(100) not null,
    created_by_subject              varchar(255),
    constraint pk_delivery_configuration_version primary key (id),
    constraint uk_delivery_configuration_version_number unique (delivery_configuration_id, version_number),
    constraint fk_delivery_configuration_version_configuration foreign key (delivery_configuration_id)
        references delivery_configuration (id),
    constraint fk_delivery_configuration_version_profile_version foreign key (connection_profile_version_id)
        references connection_profile_version (id),
    constraint fk_delivery_configuration_version_based_on foreign key (based_on_version_id)
        references delivery_configuration_version (id),
    constraint ck_delivery_configuration_version_number check (version_number >= 1),
    constraint ck_delivery_configuration_version_selection_mode check (selection_mode in ('CONDITIONS', 'ALL_FILES')),
    constraint ck_delivery_configuration_version_min_age check (min_file_age_seconds >= 0),
    constraint ck_delivery_configuration_version_max_bytes check (max_file_bytes > 0),
    constraint ck_delivery_configuration_version_post_fetch check (post_fetch_action in ('LEAVE')),
    constraint ck_delivery_configuration_version_directory check (length(btrim(remote_directory)) > 0),
    constraint ck_delivery_configuration_version_created_subject
        check (created_by_subject is null or created_by is not null)
);

create index idx_delivery_configuration_version_profile_version
    on delivery_configuration_version (connection_profile_version_id);
create index idx_delivery_configuration_version_based_on on delivery_configuration_version (based_on_version_id);

--rollback drop index idx_delivery_configuration_version_based_on;
--rollback drop index idx_delivery_configuration_version_profile_version;
--rollback drop table delivery_configuration_version;

--changeset catalogimport:014-5-delivery-configuration-file-condition
--comment Bestandsvoorwaarden van een Leveringsconfiguratie-versie: EN binnen een groep, OF tussen groepen; geen wildcards of regex (leveringsconfiguratie-design par. 3.2).

-- bookmark_name is nullable en voorlopig ongebruikt (T13): een latere bookmarkplaats DELIVERY_FILE_SELECTION
-- is dan een additieve verbreding van ck_import_definition_bookmark_usage_place. group_number en
-- sequence_number beginnen bij 0 of 1 naar keuze van de service; de database eist enkel >= 0 en uniciteit.
create table delivery_configuration_file_condition (
    id                bigint generated by default as identity,
    dc_version_id     bigint not null,
    group_number      integer not null,
    sequence_number   integer not null,
    condition_kind    varchar(30) not null,
    compare_value     varchar(200) not null,
    case_sensitive    boolean not null,
    bookmark_name     varchar(100),
    constraint pk_delivery_configuration_file_condition primary key (id),
    constraint uk_delivery_configuration_file_condition_order unique (dc_version_id, group_number, sequence_number),
    constraint fk_delivery_configuration_file_condition_version foreign key (dc_version_id)
        references delivery_configuration_version (id),
    constraint ck_delivery_configuration_file_condition_kind
        check (condition_kind in ('NAME_EQUALS', 'NAME_STARTS_WITH', 'NAME_ENDS_WITH', 'NAME_CONTAINS', 'EXTENSION_IS')),
    constraint ck_delivery_configuration_file_condition_numbers check (group_number >= 0 and sequence_number >= 0),
    constraint ck_delivery_configuration_file_condition_value check (length(btrim(compare_value)) > 0)
);

--rollback drop table delivery_configuration_file_condition;

--changeset catalogimport:014-6-acquisition-config-event
--comment Append-only auditregister van de ophaalconfiguratie (koppelen, ontkoppelen, test, hostsleutelscan, buiten gebruik). Nooit bijgewerkt, nooit verwijderd; nooit een secret of archiefpad.

-- Sortering op id, geen sequence_no (patroon 012-2/013-2). task_id, dc_version_id en profile_version_id zijn
-- alle nullable: welke gevuld zijn hangt van de soort af (een hostsleutelscan heeft enkel een profielversie).
-- reason is nullable omdat een systeem- of testgebeurtenis geen menselijke reden heeft. detail draagt nooit een
-- secret en nooit een archiefpad. source bepaalt of changed_by/changed_by_subject gevuld mogen zijn: HUMAN
-- draagt altijd een naam, SYSTEM nooit (ook niet de tekst "system").
create table acquisition_config_event (
    id                    bigint generated by default as identity,
    event_kind            varchar(30) not null,
    task_id               bigint,
    dc_version_id         bigint,
    profile_version_id    bigint,
    outcome_code          varchar(60),
    detail                varchar(500),
    reason                varchar(500),
    source                varchar(20) not null,
    changed_by            varchar(100),
    changed_by_subject    varchar(255),
    changed_at            timestamp with time zone not null,
    constraint pk_acquisition_config_event primary key (id),
    constraint fk_acquisition_config_event_task foreign key (task_id) references catalog_import_task (id),
    constraint fk_acquisition_config_event_dc_version foreign key (dc_version_id)
        references delivery_configuration_version (id),
    constraint fk_acquisition_config_event_profile_version foreign key (profile_version_id)
        references connection_profile_version (id),
    constraint ck_acquisition_config_event_kind
        check (event_kind in ('TASK_BOUND', 'TASK_UNBOUND', 'CONNECTION_TESTED', 'HOST_KEY_SCANNED', 'RETIRED')),
    constraint ck_acquisition_config_event_source
        check ((source = 'HUMAN' and changed_by is not null)
            or (source = 'SYSTEM' and changed_by is null and changed_by_subject is null)),
    constraint ck_acquisition_config_event_subject
        check (changed_by_subject is null or changed_by is not null)
);

create index idx_acquisition_config_event_task on acquisition_config_event (task_id, id);
create index idx_acquisition_config_event_dc_version on acquisition_config_event (dc_version_id, id);
create index idx_acquisition_config_event_profile_version on acquisition_config_event (profile_version_id, id);

--rollback drop index idx_acquisition_config_event_profile_version;
--rollback drop index idx_acquisition_config_event_dc_version;
--rollback drop index idx_acquisition_config_event_task;
--rollback drop table acquisition_config_event;

--changeset catalogimport:014-7-task-delivery-configuration-version
--comment Koppeling van een taak aan een Leveringsconfiguratie-versie (L2). Additief, nullable, geen backfill: bestaande taken behouden hun gedrag; A11 (hoogstens één DC-taak per koppeling) wordt in de service afgedwongen.

alter table catalog_import_task add column delivery_configuration_version_id bigint;

alter table catalog_import_task add constraint fk_catalog_import_task_dc_version
    foreign key (delivery_configuration_version_id) references delivery_configuration_version (id);

create index idx_catalog_import_task_dc_version on catalog_import_task (delivery_configuration_version_id);

--rollback drop index idx_catalog_import_task_dc_version;
--rollback alter table catalog_import_task drop constraint fk_catalog_import_task_dc_version;
--rollback alter table catalog_import_task drop column delivery_configuration_version_id;
