--liquibase formatted sql

-- Ophaalrun (SFTP): bouwstap K-4b van docs/design/leveringsconfiguratie-design.md par. 3.3, 4 en 10; beslissingslog
-- 2026-09-29 (L2: de ophaalrun IS een task_run, geen aparte fetch_run; L6: bestandskeuze met watermark en zichtbare
-- overgeslagen bestanden; A4: idempotentiesleutel in uk_delivery_idempotency; A13: delivery.source_kind = SFTP).
--
-- ADDITIEF naast 001-014, met EEN uitzondering die het design expliciet voorschrijft: 015-3 verbreedt de bestaande
-- check ck_delivery_source_kind (011-1) met SFTP. Dat is een drop + add van dezelfde constraintnaam; elke bestaande
-- waarde (UPLOAD, LOCAL_DIRECTORY) blijft geldig. Niets wordt hernoemd of van type gewijzigd.
--
-- Conventies (001/007/012/014): id bigint generated by default as identity; timestamp with time zone; rollback per changeset. Er komen GEEN subjectkolommen bij (task_run.triggered_by heeft er in 001 ook geen).

--changeset catalogimport:015-1-task-run-fetch-columns
--comment Ophaalrun op task_run (L2): herkomst van de run, gebruikte Leveringsconfiguratie-versie, uitkomst en het aantal nog wachtende bestanden (L6). Alle kolommen nullable, geen backfill.

-- trigger_source: hoe de run gestart werd. Bestaande rijen blijven null (onbekend; geen backfill - een upload-run
-- van vroeger krijgt achteraf geen verzonnen herkomst). Nieuwe runs vullen het altijd: UPLOAD (browser-upload),
-- LOCAL_DIRECTORY (beheerde servermap), MANUAL_FETCH ("Nu ophalen"), SCHEDULED_FETCH (later, scheduler S-0/S-1).
-- delivery_configuration_version_id: de DC-versie waarmee opgehaald werd (audit, par. 4.5); null bij upload/servermap.
-- outcome_code/outcome_message: uitkomst van het ophalen (par. 4.4); outcome_message bevat nooit een secret,
-- serverbanner of archiefpad. pending_file_count: aantal bestanden dat na deze run nog wacht (L6, DEFERRED).
alter table task_run add column trigger_source varchar(20);
alter table task_run add column delivery_configuration_version_id bigint;
alter table task_run add column outcome_code varchar(60);
alter table task_run add column outcome_message varchar(500);
alter table task_run add column pending_file_count integer;

alter table task_run add constraint ck_task_run_trigger_source
    check (trigger_source is null
        or trigger_source in ('UPLOAD', 'LOCAL_DIRECTORY', 'MANUAL_FETCH', 'SCHEDULED_FETCH'));
alter table task_run add constraint ck_task_run_pending_file_count
    check (pending_file_count is null or pending_file_count >= 0);
alter table task_run add constraint fk_task_run_dc_version
    foreign key (delivery_configuration_version_id) references delivery_configuration_version (id);

create index idx_task_run_dc_version on task_run (delivery_configuration_version_id);

--rollback drop index idx_task_run_dc_version;
--rollback alter table task_run drop constraint fk_task_run_dc_version;
--rollback alter table task_run drop constraint ck_task_run_pending_file_count;
--rollback alter table task_run drop constraint ck_task_run_trigger_source;
--rollback alter table task_run drop column pending_file_count;
--rollback alter table task_run drop column outcome_message;
--rollback alter table task_run drop column outcome_code;
--rollback alter table task_run drop column delivery_configuration_version_id;
--rollback alter table task_run drop column trigger_source;

--changeset catalogimport:015-2-fetch-file-observation
--comment Elk matchend bestand dat een ophaalrun bekeek, met de beslissing (L6): overgeslagen bestanden blijven altijd zichtbaar. Append-only: nooit bijgewerkt of verwijderd.

-- remote_modified_at is nullable: een SFTP-server hoeft geen wijzigingstijd te geven; zo'n bestand wordt nooit
-- gekozen (de minimale ouderdom is niet aantoonbaar) maar blijft wel zichtbaar. delivery_id is enkel gevuld bij
-- SELECTED en enkel als de levering echt geregistreerd werd (een mislukte download laat het leeg).
create table fetch_file_observation (
    id                    bigint generated by default as identity,
    task_run_id           bigint not null,
    remote_file_name      varchar(500) not null,
    byte_size             bigint not null,
    remote_modified_at    timestamp with time zone,
    decision              varchar(30) not null,
    delivery_id           bigint,
    constraint pk_fetch_file_observation primary key (id),
    constraint uk_fetch_file_observation_run_file unique (task_run_id, remote_file_name),
    constraint fk_fetch_file_observation_task_run foreign key (task_run_id) references task_run (id),
    constraint fk_fetch_file_observation_delivery foreign key (delivery_id) references delivery (id),
    constraint ck_fetch_file_observation_decision
        check (decision in ('SELECTED', 'ALREADY_FETCHED', 'TOO_YOUNG', 'TOO_LARGE', 'DEFERRED', 'OLDER_THAN_WATERMARK')),
    constraint ck_fetch_file_observation_delivery check (delivery_id is null or decision = 'SELECTED'),
    constraint ck_fetch_file_observation_byte_size check (byte_size >= 0),
    constraint ck_fetch_file_observation_name check (length(remote_file_name) > 0)
);

create index idx_fetch_file_observation_delivery on fetch_file_observation (delivery_id);

--rollback drop index idx_fetch_file_observation_delivery;
--rollback drop table fetch_file_observation;

--changeset catalogimport:015-3-delivery-source-kind-sftp
--comment A13: delivery.source_kind krijgt SFTP erbij. De enige niet-additieve stap van 015 (drop + add van dezelfde check); bestaande waarden blijven geldig.

alter table delivery drop constraint ck_delivery_source_kind;
alter table delivery add constraint ck_delivery_source_kind
    check (source_kind in ('UPLOAD', 'LOCAL_DIRECTORY', 'SFTP'));

-- Rollback lukt enkel zolang er geen SFTP-levering bestaat (de oude check zou die rij weigeren): bewust geen stille
-- omzetting van bestaande herkomst.
--rollback alter table delivery drop constraint ck_delivery_source_kind;
--rollback alter table delivery add constraint ck_delivery_source_kind check (source_kind in ('UPLOAD', 'LOCAL_DIRECTORY'));
